### ISSUE TITLE
Fri, Aug 11, 2017

### ISSUE THREAD

**Issue by vsund** [blockstack/daily-standup#108]
Yesterday: Worked on issues a user had with `blockstack-gpg` and other Blockstack tools (he's interested in contributing and likes to help implement `blockstack-gpg` in Javascript), walked him through some architecture details

Today: Published the [repository](https://github.com/ntzwrk/blockstack-files), adding more documentation to `blockstack-gpg`, resolving both issues there, looking into elaborating on details to implement `blocktsack-gpg` so that a user can easily take this, call with @pstan26, prepare a list of things I need for the app

**Comment by kantai** [comment]
Yesterday: Sorting out some issues with integration testing generally. Release of blockstack-core with support for subdomains. Working with Jack and Jude on rolling out the new version on our infrastructure.

Today: Reviewing some old security-related issues to see whether or not we need to reevaluate the priority of the issue, looking into support of AWS provisioning for browser users and app storage.

**Comment by jackzampolin** [comment]
Yesterday: Working through instrumenting Azure infrastructure. Working with Aaron and Jude to do the `0.14.4` release. 


Today: Continuing the instrument and document infrastructure. Working with Aaron and Jude on some Dockerizing `blockstack-core`

**Comment by larrysalibra** [comment]
Yesterday: Hiring tasks, name registration
Today: Merged some pull requests, meeting, payment page, register subdomain on browser

**Comment by jay-ithiel** [comment]
Wednesday: Had to go to doctors so I couldn't get much work done. Resolved some comments on the latest Pull Request for Casa.
Thurs: Went through GitHub issues people raised on Guild. Laid out groundwork for likes feature on Blogs & Comments.
Today: Implement likes feature on Guild and react-burger-menu on Casa

**Comment by guylepage3** [comment]
_**yesterday**_: 
- [x] Merge [#364: Create Contributing Guide](https://github.com/blockstack/blockstack.org/pull/364) for @estermer 
- [x] Review [#365: Remove constant iframe height](https://github.com/blockstack/blockstack.org/pull/365) on videos for @arisgk
- [x] https://github.com/blockstack/blockstack.org/issues/354: live design blockstack summit 2017 summary page
- [x] Blockstack summit 2017 email banner image design

_**today**_:
- [x] Resolve [#366: fixed images on safari mobile not scaling](https://github.com/blockstack/blockstack.org/issues/366)
- [x] Started discussion of project Kiwi w/@pstan26 
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)

_**ahead**_:
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#391: design standup – Fri, Aug 11, 2017](https://github.com/blockstack/designs/issues/391)

**Comment by muneeb-ali** [comment]
On Fri, I took calls with potential hires, worked on token framework, worked with Jack on infrastructure cleanup, and general emails/ops catch up.
