### ISSUE TITLE
Tue, Aug 15, 2017

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/daily-standup#111]
On Tue, I took calls with WSJ (multiple calls), Coindesk, and the Bitcoin Magazine. Also, took calls with our lawyers RE upcoming charter change and with USV. I was in a hiring meeting and a meeting on new verifications message. I helped Patrick with the upcoming launch and followed up some operations tasks (like paying data center bill).

**Comment by guylepage3** [comment]
_**yesterday**_: 
- [x] Setup quick static site for Kiwi project
- [x] [Create react app for kiwi project website](https://github.com/blockstackinc/signature-fund/issues/3)

_**today**_:
- [x] Finalize hero design of project Kiwi website
- [x] Start build of project Kiwi website

_**ahead**_:
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#396: design standup – Tue, Aug 15, 2017](https://github.com/blockstack/designs/issues/396)
