### ISSUE TITLE
Wed, Aug 16, 2017

### ISSUE THREAD

**Issue by vsund** [blockstack/daily-standup#112]
Yesterday: Re-adjusted the scope of the app, worked on architecture ideas, some minor fixes for `blockstack-gpg`, gathered thoughts about some community issues @jackzampolin brought up

Today: Open issues for @jackzampolin's review, update the PRD, start writing up architecture details, open issues for requirements on the respective repositories

**Comment by jackzampolin** [comment]
Yesterday: HTTPS for node.blockstack.org, 1 click deploy stuff, talked with @vsund about the [component architecture](https://forum.blockstack.org/t/component-architecture/1417/1), helped @dantrevino with his [meetup slides](https://github.com/dantrevino/blockstack-portland/)

Today: Make a `blockstack/evangelists` repo and pull in those slides. Film Explorer tutorial, keep pushing on 1 click applications.

**Comment by kantai** [comment]
Yesterday: Merged fix for CORS headers in subdomain registrar, merged support for sending owner key alongside UPDATE transactions into `develop` branch (blockstack-core, now with 20% more git flow!), tried to run down issue Larry's been having with storage+integration tests (still befuddled, added logging statements in the hope of some enlightenment).

Today: Will work on getting blockstack-core to speak HTTPS to node.blockstack.org, then move on to investigating support for using a browser-supplied key for payments in blockstack-core. The ultimate goal should be make our API endpoint more of a template-engine and stateful broadcaster, relying on clients to do the signing (the CLI would be refactored to be a RESTful client in this world), but I think that a sweeping change along those lines will need to wait until the next release (September).

**Comment by jay-ithiel** [comment]
Yesterday: Started creating tags/taggings and created a user model to lay groundwork for users to be able to follow other users. Creating a user model introduced various bugs - resolved most. Did heavy refactoring to use the user model information instead of Blockstack account information. 

Today: Will continue implementing users `follow` feature and `tags` feature.

**Comment by guylepage3** [comment]
_**yesterday**_: 
- [x] Finalize hero design of project Kiwi website
- [x] Build of project Kiwi website

_**today**_:
- [x] Pushed Signature Fund site live and then rested 
- [x] Resolve a couple spacing issues with funding page on blockstack.org
- [x] Start setup of new computer

_**ahead**_:
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#399: design standup – Wed, Aug 16, 2017](https://github.com/blockstack/designs/issues/399)
