### ISSUE TITLE
Thur, Aug 17, 2017

### ISSUE THREAD

**Issue by vsund** [blockstack/daily-standup#113]
Yesterday: Worked on a full diagram of the ecosystem for @jackzampolin, more architecture work

Today: Pushed out the changed repository, opened issues for all requirements I have, change the PRD to the new scope, begin with @estermer on Angular App Generator

**Comment by jackzampolin** [comment]
Yesterday: Worked on [`blockstack/evangelists`](https://github.com/blockstack/evangelists), Worked on https://github.com/blockstack/blockstack-core/issues/534, talked about meetups with a couple of folks and found some office space in SF.

Today: Migrate `blockstack/blockstack/evangelists` to [`blockstack/evangelists`](https://github.com/blockstack/evangelists). Working on the 1click deploy stuff. Getting the SF meetup restarted and continuing to build out the `evangelists` repo.

**Comment by jay-ithiel** [comment]
Yesterday: Made user model and followers/following feature. TONS of refactoring and resolving minor issues going from using `blockstack.loadUserData()` to a formal `User` model.

Today: Start creating user feed component and styling. Make user profile component. Create `Bookmark` model to allow users bookmark blogs to read later.

**Comment by guylepage3** [comment]
_**yesterday**_: 
- [x] Pushed Signature Fund site live and then rested 
- [x] Resolve a couple spacing issues with funding page on blockstack.org
- [x] Start setup of new computer

_**today**_:
- [x] Resolve issues with `Git LFS` so that I may download the design files onto new machine
- [x] Finalized setup of new computer
- [x] Respond to GitHub issue comments including review of new [FAQ suggestions](https://github.com/blockstack/blockstack.org/issues/374)
- [x] [Design production work and build out svg images for blockstack.org/funding partners](https://github.com/blockstack/blockstack.org/issues/375)
- [x] Merged in a couple small pull requests
- [x] Setup Sprint: 0.15
- [ ] [Resolve logo issues with funding page](https://github.com/blockstack/blockstack.org/issues/377)

_**ahead**_:
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#400: design standup – Thu, Aug 17, 2017](https://github.com/blockstack/designs/issues/400)
