### ISSUE TITLE
Fri, Aug 18 2017

### ISSUE THREAD

**Issue by jay-ithiel** [blockstack/daily-standup#114]
Yesterday: Created user feed and added styling. Made `UserProfile` profile along with basic styling. Created Bookmarks feature on `Blogs`.

Today: Link tags with blogs to filter the blogs displayed on the user's feed. Work on Casa app

**Comment by guylepage3** [comment]
_**yesterday**_: 
- [x] Resolve issues with `Git LFS` so that I may download the design files onto new machine
- [x] Finalized setup of new computer
- [x] Respond to GitHub issue comments including review of new [FAQ suggestions](https://github.com/blockstack/blockstack.org/issues/374)
- [x] [Design production work and build out svg images for blockstack.org/funding partners](https://github.com/blockstack/blockstack.org/issues/375)
- [x] Merged in a couple small pull requests
- [x] Setup Sprint: 0.15
- [x] [Worked on resolving issue with logos on funding page](https://github.com/blockstack/blockstack.org/issues/377)

_**today**_:
- [x] [Resolve breakage with logos on funding page](https://github.com/blockstack/blockstack.org/issues/377)
- [ ] [Tighten up funding page](https://github.com/blockstack/blockstack.org/issues/376)
- [ ] [Live design name registration pages](https://github.com/blockstack/blockstack-browser/issues/690)

_**ahead**_:
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#402: design standup – Fri, Aug 18, 2017](https://github.com/blockstack/designs/issues/402)
