### ISSUE TITLE
Mon, Aug 21, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/daily-standup#117]
_**last week**_: 
- [x] Setup quick static site for Signature fund page and pushed it live on Wed
- [x] Resolved some issues with blockstack.org
- [x] Setup of new computer
- [x] [Worked on live design of name registration views](https://github.com/blockstack/blockstack-browser/issues/690)

_**today**_:
- [ ] [Finalize live design of name registration views](https://github.com/blockstack/blockstack-browser/issues/690)
- [ ] [Update all button type and spacing on browser](https://github.com/blockstack/blockstack-browser/issues/693)
- [ ] [Review @estermer's README.md contribution](https://github.com/blockstack/blockstack.org/issues/378)

_**ahead**_:
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#405: design standup – Mon, Aug 21, 2017](https://github.com/blockstack/designs/issues/405)

**Comment by pstan26** [comment]
Last week: Launched [signature fund](blockstack.org/funding) (fund + bounties) (PR, recording video, content, etc.), helped get two meetups reactivated (NYC & SF) with more on the way, calls with lawyers, recorded explorer tutorial, meeting with Loomia, call with Huawei, spoke to Cloudflare about conf, worked with jeremy on funding (help from muneeb)

Today: Respond to the ~100 applications for the signature fund, plan the announcement of when the details and  of the decentralized microblog will be launched, post blog posts for summit and app fund, pay bills, call with DS

**Comment by larrysalibra** [comment]
Over weekend & today: Implemented about ~80% of manual zone file update in the browser. Weekly meeting and frontend sync up. Call with Patrick about some upcoming announcements.

**Comment by muneeb-ali** [comment]
On Mon, had our weekly meetings and a meeting of the DIG working group. I looked into defining our next hiring position with Gine and Ryan, had a meeting RE Signature Fund, worked on drafts of community updates and legal framework.
