### ISSUE TITLE
Tue, Aug 22, 2017

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/daily-standup#118]
Yesterday: Implemented about ~80% of manual zone file update in the browser. Weekly meeting and frontend sync up. Call with Patrick about some upcoming announcements.

Today: Second call with Guy around upcoming sprint frontend issues. Follow up on some slack support issues. Follow up on component discussion on forum. Finish manual zone file update. Fix a couple bugs, look into some todo list issues, ship v0.14 and document the release process in a checklist. Will also be having dinner with a VC that focuses on investments in Southeast Asia to explore getting some of their startups to build Blockstack Apps.

**Comment by guylepage3** [comment]
_**yesterday**_: 
- [x] Worked on live design of name registration views](https://github.com/blockstack/blockstack-browser/issues/690)
- [x] Weekly sprint meeting
- [x] Browser sprint meeting
- [x] One on one w/ @shea256 
- [x] [Worked on browser design](https://github.com/blockstack/blockstack-browser/issues/621)
- [x] Browser meeting with @larrysalibra discussing attack plan for completely new browser design/implementation

_**today**_:
- [ ] [Work on browser design](https://github.com/blockstack/blockstack-browser/issues/621)

_**ahead**_:
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#406: design standup – Tue, Aug 22, 2017](https://github.com/blockstack/designs/issues/406)

**Comment by vsund** [comment]
Yesterday: Looked into the app generator and more Angular stuff, worked on setting up an own explorer instance

Today: Talk with @larrysalibra about the progress of zone file updates in Browser, depending on it go on with Beacon or start on the app generator for Angular

**Comment by muneeb-ali** [comment]
Tue, I worked on the latest version of our legal framework & tax doc, polished up the community updates doc, had meetings with AngelList, meeting with Ryan RE token work, reviewed token doc draft, and worked on some operational tasks.
