### ISSUE TITLE
Wed, Aug 23 2017

### ISSUE THREAD

**Issue by jay-ithiel** [blockstack/daily-standup#119]
Yesterday: Went into Blockstack HQ to work for the day and met the team. 
Made a pull request for Guild, adding numerous features:
Users can now:
- Bookmark blogs
- Add Tags to blogs
- Follow other users

Added:
- A `/community` section, where the user can see other users people using Guild
- User profile page
- New blog feeds that show the latest blogs of the most popular tags

Today: Will merge pull request and begin creating a user feed that shows recently posted blogs of people that a user follows, per @shea256's [request](https://github.com/jay-hwang/guild/issues/21)

**Comment by guylepage3** [comment]
_**yesterday**_: 
- [x] [Worked on browser design](https://github.com/blockstack/blockstack-browser/issues/621)
- [x] Major update to http://forum.blockstack.org UI. Found quite a few breakages in;
    - [x] Dropdowns
    - [x] Navbars
    - [x] code tags
    - [x] buttons - incld. `:hover`, `:active` states
    - [x] forms
- [x] Assisted @pstan26 with Signature Bounties promo card design

_**today**_:
- [x] [Continue working on browser design for presenting tomorrow](https://github.com/blockstack/blockstack-browser/issues/621)
- [x] Review @arisgk's [video aspect ratio pull request](https://github.com/blockstack/blockstack.org/pull/365#pullrequestreview-58217885)
- [x] Reviewed and merged @estermer's [README pull request/fix](https://github.com/blockstack/blockstack.org/pull/379)
- [x] Assist @pstan26 with Signature Bounties promo card design

_**ahead**_:
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#407: design standup – Wed, Aug 23, 2017](https://github.com/blockstack/designs/issues/407)

**Comment by vsund** [comment]
Yesterday: Set up a full core node and started indexing blockchains for explorer, issued some PRs for the setup process, worked more into Angular

Today: Work on TXT records for `blockstack.js`, fix the Browser setup (still not working)

**Comment by shea256** [comment]
Yesterday:

<img width="633" alt="screen shot 2017-08-23 at 10 59 52 am" src="https://user-images.githubusercontent.com/994646/29622812-6d0264fa-87f2-11e7-9529-4bbbe2628ed9.png">

Today:

<img width="625" alt="screen shot 2017-08-23 at 11 00 29 am" src="https://user-images.githubusercontent.com/994646/29622796-65b43264-87f2-11e7-8a66-d20b704b82c4.png">

**Comment by guylepage3** [comment]
Doh! I need to start using the ToDo List app.

**Comment by muneeb-ali** [comment]
Wed, I focused on upcoming taxes and potential frameworks. Had calls with tax accountants, discovered things that need attention, and came up with potential solutions. I also looked into operational tasks for my upcoming trip to Sweden for a talk at [The Conference](https://2017.theconference.se/program/trust-in-a-post-truth-world) and at [SICS security seminar](https://www.sics.se/events/rise-sics-security-day-2017). I also caught up with email and other admin/ops tasks (like getting Gina on-boarded on Gusto, working with our lawyers on various tasks like contributor agreements etc).
