### ISSUE TITLE
Thu, Aug 24, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/daily-standup#120]
_**yesterday**_: 
- [x] [Worked on browser design](https://github.com/blockstack/blockstack-browser/issues/621)
- [x] Review @arisgk's [video aspect ratio pull request](https://github.com/blockstack/blockstack.org/pull/365#pullrequestreview-58217885)
- [x] Reviewed and merged @estermer's [README pull request/fix](https://github.com/blockstack/blockstack.org/pull/379)
- [x] Assist @pstan26 with Signature Bounties promo card design

_**today**_:
- [x] Sync up with @larrysalibra on browser
- [ ] [Finalize browser design for presenting](https://github.com/blockstack/blockstack-browser/issues/621#issuecomment-323849799)
- [ ] Review and merge @arisgk's [video aspect ratio pull request](https://github.com/blockstack/blockstack.org/pull/365#pullrequestreview-58217885)
- [ ] Begin implementation of new browser design

_**ahead**_:
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#408: design standup – Thu, Aug 24, 2017](https://github.com/blockstack/designs/issues/408)

**Comment by shea256** [comment]
Yesterday:

<img width="627" alt="screen shot 2017-08-24 at 9 39 30 am" src="https://user-images.githubusercontent.com/994646/29669079-4d692f3e-88b0-11e7-8bdc-6d7452334ca9.png">

Today:

<img width="626" alt="screen shot 2017-08-24 at 9 39 58 am" src="https://user-images.githubusercontent.com/994646/29669090-54c2c452-88b0-11e7-9b28-3d800d761994.png">

**Comment by vsund** [comment]
Yesterday: Looked into moving Beacon from React to Angular, and tried to fix Browser issues, also worked on an own explorer setup

Today: Fix Browser from yesterday, work on TXT records for `blockstack.js`

**Comment by larrysalibra** [comment]
Today: 
* v0.14.0 release
* Created a default profile page
* Publish update to update server
* Sync up with @guylepage3 
* Move large profile to default profile page

Tomorrow:
* Some project management
* port webkit stuff to develop, adjust for our mobile size

**Comment by kantai** [comment]
Yesterday: got the incremental search indexing running (and tested!) on core.blockstack.org, subdomain indexing, and improvements on the wallet generation interface for the CLI

Today: working on supporting zonefile updates for subdomains in the subdomain_registrar code, looking into a caching issue in storage discovered in integration testing on the `develop`, testing out the docker scripts and build

Note on tomorrow: I'm going to a wedding and will be on vacation through next Thursday.
