### ISSUE TITLE
Fri, Aug 25, 2017

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/daily-standup#121]
Yesterday:
* v0.14.0 release
* Created a default profile page
* Publish update to update server (ran into problems with a firebase outage. @jackzampolin added monitoring to this server for the future)
* Sync up with @guylepage3

Today:
* Move large profile to default profile page for @guylepage3 
* try out Logan's iOS project
* Project management
* Port webkit stuff to develop, adjust for our mobile size
* Travel plans

**Comment by GinaAbrams** [comment]
Yesterday: 
- Worked on Teem Access (Google Super Admin power) 
- Sent Muneeb's travel info for reimbursement 
- Ordered 2 new desks for office 
- Looked @ lights (ours are no longer available) 
- 10 new Front End candidate Emails 
- Worked on Product Manager Source Project 

Today: 
- Call with ScreenConnect for conference room video chats 
- Work on Product Sourcing - Send out 10 emails 
- Put through health care plan 
- Call w potential hire @ 4
-Send 5 more front-end candidate emails 
-Order lights & new monitor for conference room  
-Make sure Ken has all accounts set to start next week

**Comment by vsund** [comment]
Yesterday:

* Worked on core node setup
* Re-installed Browser (RAM issue from Firefox still isn't in Chrome 👍)
* Re-thought the components of `blockstack-gpg` (will transform it into a library with CLI)

Today:

* Updating `blockstack-gpg` and put it on `PyPi`
* Fix the (new) issues in the Browser
* Fix problems with the server setup

**Comment by shea256** [comment]
Attempting to post my daily scrum but my to-do list app isn't working. Copying things over currently. Might finish after the call.

**Comment by jackzampolin** [comment]
### _Yesterday_
* Worked on the [`blockstack-core`](https://github.com/blockstack/blockstack-core/pull/572) docker install. 
* Put up a PR for the [blockstack-browser](https://github.com/blockstack/blockstack-browser/pull/696) docker image.
* While those images were building I also implemented the [`blockstack api`](https://blockstack.github.io/blockstack-core/) calls in the [`blockstack-cli`](https://github.com/jackzampolin/blockstack-cli) that I had worked on stubbing out.
* Setup a [Blockstack Quay.io](https://quay.io/organization/blockstack) organization and started pushing Images there. They will be able to do automated docker image builds on our repos so this will be seamless once setup.
* Made a PR against the [`onename-api`](https://github.com/blockstackinc/onename-api) to switch calls over to `core.blockstack.org`
* Finally got the Microsoft Store build pushed! 

### _Today_
* Wrapping up work on the Docker install for both Core and Browser. Need to get with @larrysalibra on the `blockstack-browser` stuff. 
* Spend some time on the [checklists](https://github.com/blockstack/blockstack/tree/master/checklists)
* Push along PRS.
* Heading to Big Sur this weekend to celebrate my engagement and my partner's birthday!

**Comment by muneeb-ali** [comment]
Thur:
- Worked on new content for my upcoming talk in Sweden (I've been recycling the same content for over a year and want to come up with fresh content/thinking for this talk)
- Worked on content for our FAQ page 
- Looked into understanding Regulation 1.451-5(c) for taxes 
- PagerDuty
- Feedback on an upcoming announcement Patrick is working on
- Operational tasks RE upcoming travel to Sweden

Today:
- Work with Ryan on final version of community updates doc 
- Merge my updates to FAQs and polish them a bit
- Work on token whitepaper 
- Further discussions with Withum RE taxes 
- Meeting with a potential hire

**Comment by pstan26** [comment]
Yesterday: emailed investors about bounty announcements, secured funding for token portfolio app (to be built by before Oct 1), paid bunch of bills, secured date for interview with Uber's old head of Developer Platform, Intro'd to lawyers about creating legal docs for funding apps

Today: Set Summit videos on Videos page, add ToDo tutorial to blog, finalize signature fund update to go out to investors on Monday, call with developer who wants to build an invoicing app w/in next couple weeks, Dev evangelist call, Get in touch with To Do list app creator to request upgrades, call with MS ventures

**Comment by shea256** [comment]
Yesterday:

- Follow up with three potential hires
- Wire rent
- Make forum post on ethereum apps and blockstack apps
- Publish blog post on the future of the internet
- Make updates to the token economics doc
- Write one more page of the whitepaper
- Make edits to the community updates

Today:

- Work on the token whitepaper
- Finalize and send out community updates doc with Muneeb

**Comment by guylepage3** [comment]
_**yesterday**_: 
- [x] Sync up with @larrysalibra on browser
- [x] [Worked on browser design for presenting](https://github.com/blockstack/blockstack-browser/issues/621#issuecomment-323849799)

_**today**_:
- [ ] [Finalize browser design for presenting](https://github.com/blockstack/blockstack-browser/issues/621#issuecomment-323849799)
- [ ] Begin implementation of new browser design

_**ahead**_:
- [ ] Review and merge @arisgk's [video aspect ratio pull request](https://github.com/blockstack/blockstack.org/pull/365#pullrequestreview-58217885)
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#409: design standup – Fri, Aug 25, 2017](https://github.com/blockstack/designs/issues/409)

**Comment by jcnelson** [comment]
Yesterday

* migrated key file code to place all delegation and app keys as a JWT within a user's profile, in order to keep backwards-compatibility

* diagnosed fixed a wallet issue in the CLI whereby migrating a wallet from one format to another could cause the addresses to change based on whether or not the legacy code derived compressed or uncompressed public keys

* updated unit and integration tests for the wallet and key file

* began implementation of API endpoints for loading and storing profiles in the API server

* began moving away from relying on `rpc.py` to implement server-side functionality

Today:

* Work on Javascript libraries for key files and storage

* Work on integration tests for Javascript storage libraries

* Document new key file structure
