### ISSUE TITLE
Tue, Aug 29, 2017

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/daily-standup#123]
On Mon, other than our weekly meetings I: 
- Looked into DDoS protection.
- Had calls RE Public Benefit Corps.
- Updated our legal & tax doc with latest updates.
- Call with lawyers RE latest legal framework. 
- Shared an engineering execution doc for the token distribution.

Today, I'm focusing on:

- Looking at the draft Ryan had for token whitepaper and giving feedback plus expanding on it
- More work on legal/tax and ironing out issues so we can start locking down options.
- Registrar maintenance and DevOps (I'm traveling next week and would like to avoid getting PagerDuty calls then).

**Comment by GinaAbrams** [comment]
Monday: 
-Caught up on ops stuff (docs for healthcare, Jack's plane ticket, internet, task rabbit) 
-Sent over current phone screen criteria, went through Abigail's docs 
-Calibrated with Ryan/Muneeb for next steps with engineers in process 
-Went to Apple Store 
-Started new product search 
-Moved an engineer forward to tech screen process 

Plan for Today:  
-Send out 10 product and 10 front end candidate emails 
-Meeting with Pat 
-Window/ chair people coming 
-Talking with Chris from OneMonth about soundproofing other room 
-get all meeting materials ready for meeting with Abigail tomorrow 
-Work on Twitter post 
-Phone interview with Varun Aggrawal

**Comment by larrysalibra** [comment]
Yesterday/Flight: 
* Arrived in NYC
* weekly & front-end meetings
* merged pull request on blockstack.js 
* help test out docker deployment of browser
* started a document on our biggest user problems (will share later)
* browser release checklist
* started investigating cordova & other deployment options for windows/linux/mobile

Today:
* make a decision on deployment options
* merge in docker updates
* sync up with new team member
* work on name transfers

**Comment by jackzampolin** [comment]
Monday:
- Worked on getting Blockstack Docker spun up in a Windows VM to no avail. Need to source a physical Windows machine. 
- Worked with @larrysalibra to shake some bugs out of the current Docker work. That appears to be stable now. 
- Worked on getting the Regtest Environment up and running in separate containers with an eye toward running those tests more frequently.
- Answered a bunch questions on the forum. 

Today:
- Look to source a Windows machine.
- Get the Docker stuff running in the Windows environment. 
- Continue work on the Regtest environment
- Forum and Slack Q&A

**Comment by vsund** [comment]
Yesterday: Renewed the design of Beacon, set up Browser and test names

Today: Play around with @shea256's new architecture idea and try @larrysalibra's zone file update feature

**Comment by guylepage3** [comment]
_**yesterday**_: 
- [x] [Worked on browser designs](https://github.com/blockstack/blockstack-browser/issues/621#issuecomment-323849799)

_**today**_:
- [x] Sync up / front end meeting with @larrysalibra @shea256 @yknl
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] [Finalize browser design issues](https://github.com/blockstack/blockstack-browser/issues/621#issuecomment-323849799)
- [ ] Begin implementation of new browser design

_**ahead**_:
- [ ] Review and merge @arisgk's [video aspect ratio pull request](https://github.com/blockstack/blockstack.org/pull/365#pullrequestreview-58217885)
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#412: design standup – Tue, Aug 29, 2017](https://github.com/blockstack/designs/issues/412)

**Comment by Textras** [comment]
@larrysalibra what was the Cordova findings if you don't mind me asking. Did that go anywhere?
