### ISSUE TITLE
Wed, Aug 30, 2017

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/daily-standup#124]
Yesterday: hiring interview, helped new teammate get started, tested & merged in jack's docker launcher, started name transfer, did more research on browser deployment options 

Today: contain on name transfer, clean up a doc on architecture changes + share w/ team, sync up guy on redesign implementation & help with any issues

**Comment by guylepage3** [comment]
_**yesterday**_: 
- [x] [Worked on browser design issues](https://github.com/blockstack/blockstack-browser/issues/621#issuecomment-323849799)
- [x] Sync up / front end meeting with @larrysalibra @shea256 @yknl 
- [x] Interviewed Azeem
- [x] Started implementation of new browser design

_**today**_:
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] [Finalize browser design issues](https://github.com/blockstack/blockstack-browser/issues/621#issuecomment-323849799)
- [ ] Implementation of new browser design

_**ahead**_:
- [ ] Review and merge @arisgk's [video aspect ratio pull request](https://github.com/blockstack/blockstack.org/pull/365#pullrequestreview-58217885)
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`
Begin implementation of new browser des
Link to today's open source design contributor standup:
- [#414: design standup – Wed, Aug 30, 2017](https://github.com/blockstack/designs/issues/414)

**Comment by GinaAbrams** [comment]
Yesterday:
-Continued Product/Front end sourcing 
-Meeting with Pat
-Window/ chair people came
-Went to apple store & best buy
-Sent a bunch of cand. rejection emails 
-Phone interview (Product)

Today: 
-ACTUALLY send out 20 candidate product/front end messages
-Meeting with Abigail 
-Send next steps/updates to all cands in active process 
-figure out internet & lock & windows & lights & meeting software 
-Phone interview (front end)

**Comment by yknl** [comment]
Yesterday: Met with frontend team about Blockstack explorer updates and social verification in blockstack.js. Worked on switching to address-based verifications in blockstack.js

Today: Work on adding verification support for additional services in blockstack.js

**Comment by muneeb-ali** [comment]
Yesterday:
- Work on a new presentation for the upcoming conference in Sweden (deadline was yesterday).
- Work on legal/tax framework (took two calls and updated our doc).
- Work on DevOps

Today:
- Continue the legal/tax work and sync with relevant parties. 
- Work on token whitepaper draft.

**Comment by shea256** [comment]
Yesterday:

- Frontend meeting
- Twitter handle
- Token paper
- Meeting on explainer video
- Hiring interview

Today:

- Emails
- Hiring meeting
- Podcast
- Sales sheet

**Comment by jackzampolin** [comment]
Yesterday:
- Forum Q/A
- Merged in initial Docker work
- Pushed up Integration Tests for Core running in parallel

Today:
- Finish up work on integration tests for core
- Spend some time looking for SF Meetup space
