### ISSUE TITLE
Fri, Sept 1 2017

### ISSUE THREAD

**Issue by GinaAbrams** [blockstack/daily-standup#126]
Yesterday: 
-Amazon orders / office upgrades 
-Calls with Gusto, USV network call with head of talent), Oscar 
-Front-end emailing (Patrick's list)
-Product LinkedIn Project 

Today: 
-Call w Oscar 
-Run to store to grab mount for TV - Tasker coming later
-Continue emailing Patrick's project (Front End) 
-Sync with team regarding Bill.com / reimbursements 
-Start on FAQs sheet (deliverables with Abigail) 
- Copy and plan for Twitter posts re:hiring 
- Continue candidate sourcing for Product

**Comment by guylepage3** [comment]
_**yesterday**_: 
- [x] Reviewed and merged @arisgk's [video aspect ratio pull request](https://github.com/blockstack/blockstack.org/pull/365)
- [x] Started reviewing and working on Designs repo contribution guidelines w/@estermer
- [x] Worked with @estermer on new FAQ page design/implementation
- [x] Casual meeting with @shea256 @larrysalibra @yknl 
- [x] Started work on button implementation of new browser design

_**today**_:
- [x] [Finalize browser design issues](https://github.com/blockstack/blockstack-browser/issues/621#issuecomment-323849799)
- Implementation of new browser design
    - [ ] [finalize ui build buttons of new browser design](https://github.com/blockstack/blockstack-browser/issues/717)
    - [x] [ui build colors from new browser design](https://github.com/blockstack/blockstack-browser/issues/713)
    - [x] [Start on ui build typography from new browser design](https://github.com/blockstack/blockstack-browser/issues/714)
- [x] 1-on-1 with @yknl 
- [x] Quick sync up with @larrysalibra before he leaves.

_**ahead**_:
- [ ] [ui build new design forms](https://github.com/blockstack/blockstack-browser/issues/715)
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#417: design standup – Fri, Sep 1, 2017](https://github.com/blockstack/designs/issues/417)

**Comment by yknl** [comment]
Yesterday: 
- Worked on implementing html/meta tag checks for social verification in blockstack.js
- Worked on adding Instagram account verification
- Synced with Larry on test cases for social verification
- 1-on-1 with Muneeb, Jude and Patrick
- Frontend team casual meeting

Today:
- Update test cases for social verification in blockstack.js
- 1-on-1 with Ryan, Gina, Guy, Aaron
- Work on browser design implementation with Guy

**Comment by kantai** [comment]
Yesterday:
* Catching up on the status of different items in this sprint
* Worked on getting browser + api endpoint running in Windows (succeeded in getting it running with Docker Toolbox, but shipping this setup will require some significant install scripting)
* Fixed a failing integration test

Today:
* Add support for blockstack.js and blockstack-storage.js integration tests to @jackzampolin's integration test docker containers
* Look at updating the verification code in `blockstack-profiles-py` to use the social verification path in `blockstack.js` directly
* Start working on scripting the Windows docker install

**Comment by larrysalibra** [comment]
Yesterday: went over blockstack multi-reader storage with jude, jack, patrick & jay. frontend discussion with ryan, ken, and guy. meeting with aaron about windows deployment. comments on token document.

Today: Meeting with an app developer. Sync up with jude on exactly what changes we need to make to browser to support multi-reader storage. Work on name state in browser: handling names being transferred away.

**Comment by jackzampolin** [comment]
Yesterday: Integration tests in docker with @kantai and @larrysalibra. Multi-reader storage. Found Meetup space for SF! Windows docker packaging. Began work on running tests on Kubernetes.

Today: Integration tests in Kubernetes.

**Comment by muneeb-ali** [comment]
Fri: Call with tax attorney where I got feedback on our latest framework. Worked on some DevOps and registrar maintenance in preparation for my trip. Left after lunch for my trip to Sweden.
