### ISSUE TITLE
Wed, Sep 6, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/daily-standup#128]
_**yesterday**_: 
- [x] [finalize ui build buttons of new browser design](https://github.com/blockstack/blockstack-browser/issues/717)
- [x] [Start on ui build typography from new browser design](https://github.com/blockstack/blockstack-browser/issues/714)
- [x] [Worked on UI build of new design forms](https://github.com/blockstack/blockstack-browser/issues/715)
- [x] [Finalized ui build buttons of new browser design](https://github.com/blockstack/blockstack-browser/issues/717)
- Start on page cleanup
    - [x] Worked on ui build of wallet
    - [ ] Finalize ui build of sidebars
- [x] add more articles to the appearances list

_**today**_:
- [x] [Finalize UI build of new design forms](https://github.com/blockstack/blockstack-browser/issues/715)
- Page cleanup
    - [x] Finalize UI build of wallet
    - [x] Finalize UI build of sidebars
    - [ ] Finalize UI build of avatars
    - [ ] Finalize UI build of settings

_**ahead**_:
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#422: design standup – Wed, Sep 6, 2017](https://github.com/blockstack/designs/issues/422)

**Comment by yknl** [comment]
**Yesterday**

- Browser redesign structural changes - moved sidebars in profile and settings view into its own view

**Today**

- Work on browser redesign UI build - add new nav bar and secondary nav bars.
- Other structural changes as necessary
- Add LinkedIn social verification

**Comment by larrysalibra** [comment]
**Yesterday**
* travel
* meetings
* [post on location of code in state](https://forum.blockstack.org/t/duplication-of-code-state-in-blockstack/1539?u=larry)
* name transfer work
* hiring interview

**Today**
* Fixed account restoration problems
* Set default account on account restoration
* Fixed duplicate profile problem
* Name transfer testing
* Make build

**Comment by kantai** [comment]
**Yesterday**
* Meetings
* Set up automatic port forwarding, container shutdown on exit, and other clean up of blockstack + docker installer on Windows (https://github.com/kantai/blockstack-toolbox)

**Today**
* Figure out wallet password configuration for Windows
* Get "debug" mode running for blockstack-core in the docker launcher
* Test support for setting payment key via RPC in core

**Comment by GinaAbrams** [comment]
Yesterday 
-Oscar call 
-Team Meeting 
-Call w Zoom (video conferencing) 
-Updated jobs on Angellist 
-3 phone screens
-More front end reach out 

Today
-Finalize health care 
-More front-end reach out 
-Conference room upgrades 
-Start referral process

**Comment by muneeb-ali** [comment]
I took Wed off.

**Comment by jackzampolin** [comment]
Yesterday:
- Looked into using Minio for a hosted S3 backup and decided it was not an option
- Worked on running the integration tests distribuited
- Meeting about Meetup Space.

Today:
- Casa demo
- Meeting with Meetup Organizer
- NYC Meetup prep
- Distributed Integration tests
