### ISSUE TITLE
Thur, Sep 7, 2017

### ISSUE THREAD

**Issue by muneeb-ali** [blockstack/daily-standup#129]
Thur: 

- Prepare my talk for the [SICS security seminar](https://www.sics.se/events/rise-sics-security-day-2017). This will be available online and has an audience of 100+ researchers (security, distributed systems etc). 
- Catch up on Slack/email after my day off.
- Work on token whitepaper.
- Send edits for the Malmo talk video to Zach.
- Meeting with the [SICS security group](https://www.sics.se/groups/security-lab-sec).

**Comment by guylepage3** [comment]
_**yesterday**_: 
- [x] [Finalized UI build of new design forms](https://github.com/blockstack/blockstack-browser/issues/715)
- Page cleanup
    - [x] Finalized UI build of wallet
    - [x] Finalized UI build of sidebars
    - [x] Started working on UI build of settings

_**today**_:
- Page cleanup
    - [ ] Finalize UI build of avatars
    - [ ] Finalize UI build of settings
- [ ] [Live design name registration views](https://github.com/blockstack/blockstack-browser/issues/690)

_**ahead**_:
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#423: design standup – Thu, Sep 7, 2017](https://github.com/blockstack/designs/issues/423)

**Comment by pstan26** [comment]
*Yesterday*:
Ran NYC Meetup in evening
Daily app review from Sig Fund
Improved CRM -- bounties as companies, matching devs to projects
Scheduled Security Audit with RL

*Today*:
Calls with.. 
Ops Sec contact
NodeFarm w/ Larry
Jim D for sourcing engineers
Rising Tide
YouNow (Livestreaming videos)
Video editing w/ zach (berlin, meetup, etc)
Secure blog bounty lead
Re-engage Google+ UX fellow
Further improve funnel for Sig Fund

**Comment by GinaAbrams** [comment]
Yesterday 
-Oscar calls 
-Front End Reach out 
-Met with Ryan for referral process 

Today
-Get Jack healthcare 
-Meet with more of team for referrals 
-Front-end reach out
-Sync up on bill.com and ops details

**Comment by yknl** [comment]
**Yesterday**
- Worked on browser redesign build - secondary nav bar component, updated the profile view

**Today**
- Continue to work on browser redesign build - update the all avatars view in profile, build out the main nav
- Add LinkedIn account verification to blockstack.js

**Comment by jackzampolin** [comment]
Yesterday:
- NYC Meetup Prep and Preso
- Meeting w/ SF Meetup Organizer
- Distributed Integration Tests
- Meetings

Today:
- Blockstack core release (making checklist)
- Distributed Integration tests
- Multireader storage
- Finalize SF Meetup plans

**Comment by kantai** [comment]
Yesterday:
* NYC Meetup Prep
* Add password prompt to windows installer (even once payment keys are stored in browser, core remains in the trust domain --> it needs a password for now)
* Begin work on supporting payment key passing

Today:
* Release blockstack-core 0.14.5 with Jack
* Call for infrastructure/operational security audit
* Add tests for supporting payment key passing (this is going to remain in a feature branch for now)
* Help with some bug hunting on account restores

**Comment by larrysalibra** [comment]
Today: 
* prepared v0.15.0 release branch
* web site updates
* meeting with node farm
* improved & tested account restoration process
* notifications for name transfer & merged
* Will make v0.15.0 release 

Tomorrow:
* review blockstack.js verification changes & integrate 
* integrate multi-reader storage into browser

**Comment by shea256** [comment]
Yesterday:

- Paper updates
- Hiring work
- Emails and task coordination

Today:

- Day off
