### ISSUE TITLE
Fri, Sep 8, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/daily-standup#130]
_**yesterday**_: 
- [x] Figured out new sub-feature method in `git flow`
- [x] Worked with new designer Ben Dunkle to bring him up to speed with contributing design to Blockstack.
- [x] Met with Patrick and Zach on Berlin event
- Page cleanup
    - [x] Worked UI build of settings

_**today**_:
- Page cleanup
    - [ ] Finalize UI build of avatars
    - [ ] Finalize UI build of settings
- [ ] [Live design name registration views](https://github.com/blockstack/blockstack-browser/issues/690)

_**ahead**_:
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#424: design standup – Fri, Sep 8, 2017](https://github.com/blockstack/designs/issues/424)

**Comment by yknl** [comment]
**Yesterday**
- Sync up with frontend team on git flow branching issues
- Added support for LinkedIn account verification to blockstack.js
- Browser redesign build - Updated all avatars view

**Today**
- Browser redesign build - View profiles page, various pieces in profile and avatars page

**Comment by kantai** [comment]
**Yesterday**

* Core 0.14.5.0 + 0.14.5.1 release (two releases in 1 day!)
* Hotfix for some default port configuration issues
* Worked on support for passing payment key

**Today**

* More time with passing payment keys
* Adding protocol handler to windows

**Comment by GinaAbrams** [comment]
Yesterday: 
-Synced up with Jack re:healthcare
-Meet with more of team for referrals (Aaron + Jude) 
-Front-end reach out  

Today: 
-Run to hardware store for sound proof materials
-MORE FRONT END REACH OUT 😁 
-Sync with Patrick re: bill.com 
-Do some office organization (onemonth -> blockstack transition)

**Comment by muneeb-ali** [comment]
Fri: 

- Meeting with [Adam Dunkels](https://en.wikipedia.org/wiki/Adam_Dunkels). 
- The flight back to NYC.
