### ISSUE TITLE
Thu, Sep 14, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/daily-standup#134]
_**monday, tuesday, wednesday**_: 
- Was under the weather from Monday afternoon, Tuesday, Wednesday.. But managed to get the following done;
- [x] Finalized UI build of navbars on browser
- [x] Reviewed browser with @yknl 
- [x] Reviewed Berlin items with @pstan26 
- [x] Reviewed and replied to Ben's, Aris' and Eric's issues
- [x] Reviewed and merged @estermer's blockstack.org fix https://github.com/blockstack/blockstack.org/pull/389
- [x] [Clean up wallet view](https://github.com/blockstack/blockstack-browser/issues/743)

_**today**_:
- [x] [Signature Berlin tasks](https://github.com/blockstack/designs/issues/421) & coordination with designer for files for @pstan26 
    - [x] Print production on the chosen "Signature Berlin" logo that that the designer provided.
    - [x] Use opaque Berlin city background with newly created logo in foreground to create eventbrite image 
- Finalize browser for release to a 90-95%
    - [x] Secondary nav review - (review all states) - https://github.com/blockstack/blockstack-browser/issues/763
    - [ ] Main avatar review - https://github.com/blockstack/blockstack-browser/issues/764
    - [ ] Name registration process cleanup - https://github.com/blockstack/blockstack-browser/issues/690
    - Settings cleanup - 
        - [ ] Storage live design
    - [ ] "All Avatars" style clean up
    - [ ] On-boarding touch up
    - [ ] Make “Remove Account” button red/warning - https://github.com/blockstack/blockstack-browser/issues/745
    - [ ] Check all active states
    - [ ] Check all forms

_**ahead**_:
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] [Quick css live design update to to do list app](https://github.com/blockstack/blockstack-todos/issues/6)
- [ ] [Quick once over of SCSS for Guild app](https://github.com/jay-hwang/guild/issues/10)
- [ ] [Ongaku Ryoho design review](https://github.com/blockstack/designs/issues/384)
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#429: design standup – Thu, Sep 14, 2017](https://github.com/blockstack/designs/issues/429)

**Comment by yknl** [comment]
**Yesterday**
- Finish up API changes for `validateProofs` in blockstack.js
- Fix minor browser redesign UI issues, nav bar flickering
- Resolve conflicts and merge `feature/redesign` and `develop` branch in `blockstack-browser`
- Finish setting up `blockstack-explorer` and familiarize with the code base

**Today**
- Work on `blockstack-explorer` updates
- Investigate and fix issues in `blockstack-browser` redesign
- Minor change of social proof verification text in `blockstack.js`

**Comment by pstan26** [comment]
**Yesterday**
- confirmed Berlin event venue [axica](https://www.axica.de/en/)
- worked with pro-bono designers on logo design for berlin event
- worked with app developers (Ethan and co) working on virtual R&D lab
- send agreement to arthur for software license
- spoke with PDF designer Hannah (she is sending more examples of her work soon)
- call with OpenOcean VC about funding apps

**Today**
- Tax deadline for withum
- email PR firm with next steps
- find someone to teach mike freedman class
- Call with Lawyers (Matt T.)
- Call with Symmitree (building app)
- draft pb corp post
- opsec confirmation and next steps

**Comment by kantai** [comment]
Yesterday
* Added authentication and s3 driver to gaia hub
* First implementation of gaia-hub-driver for blockstack-core, it worked and was super simple and fast! no more indexes, yay!

Today
* Merge readme changes and docker script updates from @jackzampolin to (hopefully) clean up the installation instructions for Linux, Windows, Mac
* More storage driver work for core
* Either: Work on the shared storage authentication/setup path in browser OR: work on the social proof validation in the shared storage service.

**Comment by jackzampolin** [comment]
_yesterday_
- Updated browser dockerfile to build from source. 
- Worked on hub with @kantai. Have both azure and was implemented
- Pushed some updates to the install process to vote readme and blockstack.org

**Comment by larrysalibra** [comment]
Thursday:
* had a 1-on-1 with ryan
* wrote up discussion with ryan about verifications
* interviewed a potential hire
* tried multi-reader storage again based on jude's feedback
* discuss migration path for multi-reader storage

**Comment by GinaAbrams** [comment]
Yesterday:
-sync w Bill re hiring
-Hiring reach out/ PM process details
-Ops stuff (lock, seeing what lights we can get etc.) 

Today: 
-call with Muneeb's referral (for more referrals) 
-Senior front-end reach out for us/Bill 
-More Bill.com / ops stuff

**Comment by pstan26** [comment]
*Yesterday*
- drafted email to Onename users
- planned bounty for token app portfolio manager
- emailed speakers for Berlin
- Got Snowden contact (woot woot)
- We contacted every last person in the Signature Fund funnel

*Today*:
- Finalize OpSec with RL
- Email first batch of Onename users
- meeting with Josh at Compound
- get back to LaunchSquad with proposal
- Move on action items for Blockfolio competitor
- Call with lawyers on rules for Bounty
- Ping Nick S
- Tezos agreement
- Begin sourcing materials and drafting PDF for token
- Check in with Aaron from Optic Sky on Vid production

**Comment by jcnelson** [comment]
Yesterday

* Implement segwit support

Today

* Implement segwit support
