### ISSUE TITLE
Fri, Sep 14, 2017

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/daily-standup#135]
Yesterday:
* wrote up discussion with ryan about verifications
* tried multi-reader storage again based on jude's feedback
* discuss migration path for multi-reader storage with aaron and jude
* frontend sync up with ken & guy
* prioritized explorer tasks

Today: 
* update blockstack.js docs to manage storage expectations
* some hiring tasks
* review verifications
* merge webkit into redesign & audit
* review hard fork doc
* work on re-enabling browser wall and sending its payment key to core

**Comment by guylepage3** [comment]
_**yesterday**_: 
- [x] [Signature Berlin tasks](https://github.com/blockstack/designs/issues/421) & coordination with designer for files for @pstan26 
    - [x] Print production on the chosen "Signature Berlin" logo that that the designer provided.
    - [x] Use opaque Berlin city background with newly created logo in foreground to create eventbrite image 
- [x] [Secondary nav review - (review all states)](https://github.com/blockstack/blockstack-browser/issues/763) on browser
- [x] [Started on main avatar review](https://github.com/blockstack/blockstack-browser/issues/764)
- [x] Token designer coordination
- [x] Reviewed a couple of Alex's pull requests as well as Aris and Eric's PR's.
- [x] Started audit of frontend engineering of browser and created issues - Working state of browser is not at 100%.

_**today**_:
- [x] Sync up with @larrysalibra & @yknl 
- [x] Token frontend meeting with @MechanicalHuman & @pstan26 
- [ ] Provide details for webkit native window to mobile size and look for @larrysalibra 
- [ ] Setup regtest - https://github.com/blockstack/blockstack-core/blob/master/docs/interactive_regtest_macos.md
- [x] Review and feedback on @estermer's [integrate ui from api.onename.com for FAQ section of blockstack.org](https://github.com/blockstack/blockstack.org/issues/380#issuecomment-329827933)
- [x] Review and merge @arisgk's [update funding page to use EmbedYouTube component pull request](https://github.com/blockstack/blockstack.org/pull/391#pullrequestreview-63110327)

Finalize browser for release to a 90-95%
- [x] Main avatar review - https://github.com/blockstack/blockstack-browser/issues/764
- [x] add border to all input fields on default forms - https://github.com/blockstack/blockstack-browser/issues/780
- [x] Review all forms - https://github.com/blockstack/blockstack-browser/issues/774
- [ ] Storage live design - https://github.com/blockstack/blockstack-browser/issues/772
- [ ] Name registration process cleanup - https://github.com/blockstack/blockstack-browser/issues/690
- [ ] "All Avatars" style clean up - https://github.com/blockstack/blockstack-browser/issues/736
- [ ] On-boarding touch up - https://github.com/blockstack/blockstack-browser/issues/651
- [x] Make “Remove Account” button red/warning - https://github.com/blockstack/blockstack-browser/issues/745
- [ ] Review all active states - https://github.com/blockstack/blockstack-browser/issues/773
- [ ] Center icons to home screen (@larrysalibra) - https://github.com/blockstack/blockstack-browser/issues/775
- [ ] Final audit of frontend engineering of browser

_**ahead**_:
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] Quick css live design update to to do list app
- [ ] Quick once over of SCSS for Guild app
- [ ] Ongaku Ryoho design review
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#430: design standup – Fri, Sep 15, 2017](https://github.com/blockstack/designs/issues/430)

**Comment by GinaAbrams** [comment]
Yesterday: 
-call with Muneeb's referral (for more referrals) 
-Senior front-end reach out for us/Bill 
-More Bill.com / ops stuff 
-Ordered Swag/stickers for meet-ups 
-Some edits to careers page 
-Call w ATS Software co 

Today: 
-More calls w/ ATS / A-list people 
-Call w meeting scheduler 
-Sync w Ryan & team re: hiring 
-Meeting w Abigail 
-Candidate sourcing 
-Work on conference room upgrades

**Comment by yknl** [comment]
**Yesterday**
- Frontend sync with larry and guy
- Work on bugs/changes in browser, secondary nav states, edit photo not working
- Change social proof verification message in `blockstack.js`
- Improved Github proof verification by verifying raw gist instead
- Work on `blockstack-explorer` updates

**Today**
- Fix edit photo bug in `blockstack-browser`
- Work on switching `blockstack-explorer` to use `blockstack-core` api

**Comment by muneeb-ali** [comment]
Yesterday:
- Video recording for most of the day
- Meeting with Ryan RE token whitepaper 
- Meeting with lawyers RE corporate tasks
- Work on benefit corp

Today: 
- Look into legal work for benefit corp and send it out
- Sync up on whitepaper and take the lock from Ryan

**Comment by pstan26** [comment]
Yesterday:
- worked with Gina to get swag delivered to 3 meetup locations around the world (cost-optimized)
- call with lawyers on corporate tasks
- secured event space for Berlin event
- final logos created for Berlin event
- Call with Symmitree (refugee startup)
- Paid Optic Sky, zach valenti

Today:
- Pay Jay last payment
- 1:1 with muneeb
- Evangelist weekly meeting
- meeting with Alid, who wrote great blogpost
- upload explorer tutorial (finalized)
- schedule call with Launchsquad
- opsec next steps

**Comment by kantai** [comment]
Yesterday:
* Merged and updated install instructions for browser on linux/windows with docker
* Worked on the gaia hub code, adding an endpoint to obtain the challenge that needs to be signed
* Added (hacky?) support for connecting to the gaia hub to a feature branch on browser

Today:
* More fun with gaia hub
* Add notes on the protocol handler to Linux install (or script?)

**Comment by shea256** [comment]
Yesterday:

- Video shoot
- Call w/ lawyers
- White paper
- Write up sale mechanics
- Meeting w/ potential hire
- Meeting with Muneeb on whitepaper

Today:

- Meeting with Muneeb on whitepaper
- Move the legal work forward on the public benefit corp
- Hiring meeting with Abigail
