### ISSUE TITLE
Mon, Sep 18, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/daily-standup#136]
_**friday, saturday, sunday**_: 
- [x] Sync up with @larrysalibra & @yknl 
- [x] Token frontend meeting with @MechanicalHuman & @pstan26 
- [x] Review and feedback on @estermer's [integrate ui from api.onename.com for FAQ section of blockstack.org](https://github.com/blockstack/blockstack.org/issues/380#issuecomment-329827933)
- [x] Review and merge @arisgk's [update funding page to use EmbedYouTube component pull request](https://github.com/blockstack/blockstack.org/pull/391#pullrequestreview-63110327)
- [x] Main avatar review - https://github.com/blockstack/blockstack-browser/issues/764
- [x] add border to all input fields on default forms - https://github.com/blockstack/blockstack-browser/issues/780
- [x] Make “Remove Account” button red/warning - https://github.com/blockstack/blockstack-browser/issues/745
- [x] Review all forms - https://github.com/blockstack/blockstack-browser/issues/774
- [x] Provide details for webkit native window to mobile size and look for @larrysalibra - https://github.com/blockstack/blockstack-browser/issues/697
- [x] Storage live design - https://github.com/blockstack/blockstack-browser/issues/772

_**today**_:
- [x] "All Avatars" style clean up - https://github.com/blockstack/blockstack-browser/issues/736
- [x] Review all active states - https://github.com/blockstack/blockstack-browser/issues/773
- [x] Center icons to home screen (@larrysalibra) - https://github.com/blockstack/blockstack-browser/issues/775
- [x] add navbar & secondary nav margin bottom - https://github.com/blockstack/blockstack-browser/issues/786
- [x] Review and merge @kkomaz's pull request - [Change remove account button to red](https://github.com/blockstack/blockstack-browser/pull/753)
- [x] Review and merge @kkomaz's pull request - [Account delete confirmation step modal create](https://github.com/blockstack/blockstack-browser/pull/760)
- [x] Review and merge @kkomaz's pull request - [Add cursor pointer to button and a tags](https://github.com/blockstack/blockstack-browser/pull/771)
- [ ] Name registration process cleanup - https://github.com/blockstack/blockstack-browser/issues/690
- [ ] On-boarding touch up - https://github.com/blockstack/blockstack-browser/issues/651
- [x] Priority! Setup regtest - https://github.com/blockstack/blockstack-browser/issues/795
- [ ] Final audit of frontend engineering of browser

_**ahead**_:
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] Quick css live design update to to do list app
- [ ] Quick once over of SCSS for Guild app
- [ ] Ongaku Ryoho design review
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#431: design standup – Mon, Sep 18, 2017](https://github.com/blockstack/designs/issues/431)

**Comment by yknl** [comment]
**Fri + Weekend**
- Sync with @larrysalibra & @guylepage3 on browser
- Worked on browser issues - "Add Username" button, owner address tooltip, edit button bug, add back button to on-boarding identity key page

**Today**
- Attend to browser issues as they arise
- Work on switching `blockstack-explorer` to blockstack core api

**Comment by shea256** [comment]
Friday & this weekend:

- Met with a quality potential PM hire
- Collaborated with Muneeb on whitepaper details
- Incorporated Muneeb’s feedback into the white paper and did the handover
- Added pagination to the blog
- Fixed the copy on the site for user product update / newsletter sign-ups
- Shared a proposal with the team
- Closed the token sale package purchase

Today:

- Founder meeting with Muneeb
- Team meeting
- Review of profiles tab in browser
- PR call
- Whitepaper meeting with Muneeb
- Preparation for AL meeting
- AL meeting

**Comment by jackzampolin** [comment]
_last week_:
- Gaia Hub implementation
- Docker builds for each product for each commit
- Install instructions update
- Meetup planning

_today_:
- Team meeting
- Cleanup Hub and Docker work from last week
- Meetup planning
- Continuing the hub work

**Comment by muneeb-ali** [comment]
Mon:
- Early morning meeting with Zavain
- Started weekly sync-up with Larry
- Weekly meeting
- Meeting with AngelList RE product 
- Discussions with Ryan RE whitepaper details

**Comment by jcnelson** [comment]
Yesterday

* Implement hard fork features

Today

* Implement hard fork features
* Storage meeting re: Gaia hubs
