### ISSUE TITLE
Tue, Sep 19, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/daily-standup#137]
Quick Link: [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**yesterday**_: 
- [x] "All Avatars" style clean up - https://github.com/blockstack/blockstack-browser/issues/736
- [x] Review all active states - https://github.com/blockstack/blockstack-browser/issues/773
- [x] Center icons to home screen (@larrysalibra) - https://github.com/blockstack/blockstack-browser/issues/775
- [x] add navbar & secondary nav margin bottom - https://github.com/blockstack/blockstack-browser/issues/786
- [x] Review and merge @kkomaz's pull request - [Change remove account button to red](https://github.com/blockstack/blockstack-browser/pull/753)
- [x] Review and merge @kkomaz's pull request - [Account delete confirmation step modal create](https://github.com/blockstack/blockstack-browser/pull/760)
- [x] Review and merge @kkomaz's pull request - [Add cursor pointer to button and a tags](https://github.com/blockstack/blockstack-browser/pull/771)
- [x] Priority! Setup regtest - https://github.com/blockstack/blockstack-browser/issues/795

_**today**_:
- [x] Review and merge @jackzampolin's pull request - https://github.com/blockstack/blockstack.org/pull/390
- [x] Blog image
- [x] Event video asset production
- [x] Review adding container to browser - https://github.com/blockstack/blockstack-browser/issues/803
- [ ] Name registration process cleanup - https://github.com/blockstack/blockstack-browser/issues/690
- [ ] On-boarding touch up - https://github.com/blockstack/blockstack-browser/issues/651
- [ ] Final audit of frontend engineering of browser
- [ ] Start on blockstack.org review

_**ahead**_:
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] Quick css live design update to to do list app
- [ ] Quick once over of SCSS for Guild app
- [ ] Ongaku Ryoho design review
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#433: design standup – Tue, Sep 19, 2017](https://github.com/blockstack/designs/issues/433)

**Comment by shea256** [comment]
Yesterday:

- Founder meeting with Muneeb
- Team meeting
- Review of profiles tab in browser
- PR call
- Whitepaper meeting with Muneeb
- Preparation for AL meeting
- AL meeting

Today:

- Check back in on the signatures
- Help with blog post publishing
- Work with Patrick to draft the Onename email
- Work with Larry to do the Onename development handoff
- Couple of meetings

**Comment by yknl** [comment]
**Yesterday**
- Fix set default profile bug in browser
- Fix nav state issue in browser
- Setup Insight API on bitcore node for @jackzampolin 
- Setup regtest with help from @kantai and test name registration in browser

**Today**
- Resolve any remaining browser issues
- Work on switching explorer to use blockstack-core api

**Comment by jackzampolin** [comment]
_yesterday_
- Worked on calculating the total BTC invested in the Blockstack system
- Built out deployment and deployed [`gaia-hub`](https://github.com/blockstack/gaia/tree/master/hub)
- Worked on `gaia-hub` testing to make more robust
- Meetup organization

_today_
- Sprucing up the [Intro to Blockstack](https://github.com/blockstack/evangelists/tree/master/overview) and [Blockstack ToDo](https://github.com/blockstack/evangelists/tree/master/todo) talks for the meetup tomorrow!
- Helping out with the `gaia-hub` where I can
- Calculate BTC for whole Blockstack system

**Comment by muneeb-ali** [comment]
Tue:
- Meeting with Albert
- Meeting with Ryan RE whitepaper and other deliverables/strategy 
- Call with lawyers RE upcoming tasks 
- Incorporated feedback on PBC announcement draft

**Comment by jcnelson** [comment]
Yesterday

* Implement hard fork features

Today

* Implement hard fork features
