### ISSUE TITLE
Wed, Sep 20, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/daily-standup#138]
Quick Link: [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**yesterday**_: 
- [x] Review and merge @jackzampolin's pull request - https://github.com/blockstack/blockstack.org/pull/390
- [x] Blog image
- [x] Event video asset production
- [x] Spent time recruiting more developers, providing them with tasks and on-boarding

_**today**_:
- [x] Blockstack.org meeting with @muneeb-ali & @GinaAbrams 
- [ ] ~~Review adding container to browser - https://github.com/blockstack/blockstack-browser/issues/803~~ - passed over to @yknl 
- [ ] ~~Name registration process cleanup - https://github.com/blockstack/blockstack-browser/issues/690~~ - passed over to @yknl 
- [ ] ~~On-boarding touch up - https://github.com/blockstack/blockstack-browser/issues/651~~ - passed over to @yknl 
- [ ] ~~Final audit of frontend engineering of browser~~ - passed over to @yknl 
- [ ] Start on blockstack.org design and build

_**ahead**_:
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] Quick css live design update to to do list app
- [ ] Quick once over of SCSS for Guild app
- [ ] Ongaku Ryoho design review
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#436: design standup – Wed, Sep 20, 2017](https://github.com/blockstack/designs/issues/436)

**Comment by kantai** [comment]
*Yesterday*
* Push gaia_hub driver to develop on core
* Wrap up initial work on gaia_hub support in browser (open PR)
* Fix a header-bug in the gaia-hub
* Add "tag"-specification to the windows installer makefile in packaging

*Today*
* Implement social proof verification in gaia-hub

**Comment by yknl** [comment]
**Yesterday**
- Work on setting up blockstack-explorer to use the core api

**Today**
- Continue working on blockstack-explorer, replace explorer API endpoints with core endpoints

**Comment by shea256** [comment]
Yesterday:

- Check back in on the signatures
- Help with blog post publishing
- Work with Patrick to draft the Onename email
- Work with Larry to do the Onename development handoff
- Couple of meetings
- Met with Patrick on the bounty announcement
- Went through all of our stories and made sure they’re on track
- Followed up with Patrick on the status of the security reviews

Today:

- Help with the blog post announcement
- Onename email has to go out
- Get a list of names that are expiring from Jack or Jude
- Work with Patrick on security reviews, add two more contractors
- Follow up with AngelList on action items

**Comment by jackzampolin** [comment]
_yesterday_
- Gaia hub bug fixes
- Calculated the # of BTC burned by Blockstack
- Meetup Prep

_today_
- IDEO call and talk
- Meetup Organization
- Meetup!

**Comment by muneeb-ali** [comment]
Wed:
- Pushed out the [Public Benefit Corp announcement](https://blockstack.org/blog/public-benefit-corp)
- Worked with lawyers/shareholder on legal stuff and filing PBC change
- Blockstack.org proposal for upcoming changes (Guy & Gina)
- Meeting with Xan

**Comment by jcnelson** [comment]
Yesterday

* Implement hard fork 

Today

* Implement hard fork
