### ISSUE TITLE
Thu, Sep 21, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/daily-standup#139]
Quick Link: [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**yesterday**_: 
- [x] Blockstack.org meeting with @muneeb-ali & @GinaAbrams - pulled from browser work to work on blockstack.org and token deliverables.
- [ ] ~~Review adding container to browser - https://github.com/blockstack/blockstack-browser/issues/803~~ - passed over to @yknl 
- [ ] ~~Name registration process cleanup - https://github.com/blockstack/blockstack-browser/issues/690~~ - passed over to @yknl 
- [ ] ~~On-boarding touch up - https://github.com/blockstack/blockstack-browser/issues/651~~ - passed over to @yknl 
- [ ] ~~Final audit of frontend engineering of browser~~ - passed over to @yknl 
- [x] Browser sync up with @yknl to hand off browser work
- [x] Managed community members and assigned tasks
- [x] Started on blockstack.org design research
- [x] Update to PBC blog post image
- [x] Worked with @zachvalenti and @pstan26 on the positioning of assets for the berlin video
- [x] blockstack meetup q&a video template - https://github.com/blockstack/designs/issues/438
- Left early will make up time on weekend.

_**today**_:
❗️**Currently blocked** ❗️
- [ ] Continue on blockstack.org design / build once deliverables have been signed off on.

_**ahead**_:
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] Quick css live design update to to do list app
- [ ] Quick once over of SCSS for Guild app
- [ ] Ongaku Ryoho design review
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`

Link to today's open source design contributor standup:
- [#439: design standup – Thu, Sep 21, 2017](https://github.com/blockstack/designs/issues/439)

**Comment by yknl** [comment]
**Yesterday**
- Work on blockstack-explorer, started replacing API endpoints with core endpoints
- Adjust blockstack-browser max-width for optimal display on wider screens
- Designed new on-boarding icons and updated welcome modal
- Fixed modal form margin issues
- Audit of browser for release

**Today**
- Fix browser bug where no default profile is set after restore profile
- Update the photo upload UI in browser for redesign
- Work on blockstack-explorer

**Comment by pstan26** [comment]
Yesterday:
- moved OpSec items forward across three different consultants
- call with lawyers on bounty rules for token portfolio app (final call today)
- outlined product requirements document for token portfolio app
- drafted design issue for token portfolio app bounty release
- Got Bill Hessert to agree to create landing page, logo, for app addition
- Finalized Signature Berlin event [promo video](https://drive.google.com/file/d/0B0nLkLXuZ60EYTgyTkhaalM2VFE/view)
- Sent transfer update to ~200 Onename users to prepare to transfer name to Blockstack browser


Today:
- walk through of software handoff from Tezos
- edit blockstack.org doc
- meeting with Boris Wertz for lunch
- bounty followup with lawyers
- outreach to reporters about bounty
- submit request for how to proceed with LaunchSquad
- put together materials for token PDF

**Comment by larrysalibra** [comment]
Today:
* cleaned up photo page
* fixed a bug where unable to use add photo page after buying user name
* removed clickable white space in on-boarding screens
* fixed a bug where adding a username changed the default id
* merged in search username color fixes
* tested against blockstack-todos
* tested against hello blockstack
* tested against forum 
* 1-on-1 with ken
* ship 0.16
* blockstack.org paper doc

Tomorrow
* integrate gaia hub pull request into browser
* additional sprint tasks

**Comment by GinaAbrams** [comment]
Yesterday:
-Meeting w Muneeb and Guy about Blockstack,org 
-Meeting with a WiFi provider 
-2 ATS Meetings
-Candidate reach out and  meeting for Bill (4 profiles now- 2 more immediate) 
-Started on Press consolidation for website 
-Worked w Tasker to send out Swag - (then had to enter a lot of addresses in Fedex - will be finished today) 

Today:
-2 more meetings w candidates for Bill 
-Work on Press stuff for website 
-Start on-boarding playbook 
-Finish sending out Swag

**Comment by kantai** [comment]
Yesterday:
* Documentation clean-up
* Worked on obtaining list of expiring names
* Start on supporting social proof verification in hub

Today:
* Blockstack release
* Continue social proof verification in gaia-hub

**Comment by shea256** [comment]
Yesterday:

- Chased down signatures for the PBC announcement
- Worked with Patrick on the plan for the Onename email
- Sent out the first batch of emails to Onename users
- Worked with Muneeb on the economics document
- Looped in Patrick with two security professionals

Today:

- Handoff meeting with Tezos
- Meeting to discuss the website
- Send out next batch of Onename emails
- Move forward with security reviews
- Follow up with AL

**Comment by muneeb-ali** [comment]
On Thur, I was sick and slept in. I posted more updates in the [Fri scrum](https://github.com/blockstack/daily-scrum/issues/140#issuecomment-331449173).

**Comment by jackzampolin** [comment]
_yesterday_
- Meetup!
- Odds and ends

_today_
- Work on gaiahub 
- Work on integration tests 
- Clean out inbox

**Comment by jcnelson** [comment]
Yesterday

* Implement hard fork features

Today

* Implement hard fork features
