### ISSUE TITLE
Fri, Sep 22, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/daily-standup#140]
Quick Link: [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**yesterday**_: 
- [x] Blockstack.org & UI design research
- [x] Managed community members and assigned tasks
- [x] Blockstack.org meeting `#2` w/@muneeb, @larrysalibra, @shea256, @GinaAbrams 
- [x] Started [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [x] Started [#398: Rebuild Token Banner to be an `alert` banner](https://github.com/blockstack/blockstack.org/issues/398)
- [x] Blockstack Meetup Q&A video template - https://github.com/blockstack/designs/issues/438

_**today**_:
- [x] Review browser design issues and community member responses
- [ ] Finalize [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [ ] Finalize [#398: Rebuild Token Banner to be an `alert` banner](https://github.com/blockstack/blockstack.org/issues/398)
- [ ] [#400: Update navbar items](https://github.com/blockstack/blockstack.org/issues/400)
- [ ] Work on [new About page design](https://github.com/blockstack/blockstack.org/issues/401)

_**ahead**_:
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] Quick css live design update to to do list app
- [ ] Add grid to `browser-v0.11.sketch` file

Link to today's open source design contributor standup:
- [#440: design standup – Fri, Sep 22, 2017](https://github.com/blockstack/designs/issues/440)

**Comment by yknl** [comment]
**Yesterday**
- Fix browser bug where no default profile is set after restore profile
- Final review of browser for release
- 1 on 1 with @larrysalibra 
- Work on explorer updates

**Today**
- Meeting with @shea256 @larrysalibra  for KYC/AML API
- Finish update on blockstack explorer to use core api
- Update explorer address page to list profile cards

**Comment by GinaAbrams** [comment]
Yesterday:
-Meetings w candidates for Bill 
-Meeting with Bill on reqs
-Meeting about Blockstack org 
-Sync w Guy on Press stuff for website
-Checked in about ops stuff - Bill.com + healthcare for Jack 

Today: 
-Calls to service providers : AT&T about hotspots (went to store this AM)  Call current ISP about refund, Fob replacement 
-Finally send out swag (fedex problems) 
-Quick meeting w candidate for Bill 
-Send Guy images for press section 
-On-boarding playbook

**Comment by muneeb-ali** [comment]
Yesterday: 
- I was sick and slept in. 
- blockstack.org sync
- Work on whitepaper v2
- Scheduled whitepaper reviews

Today:
- Focused on whitepaper v2 (main thing)
- Meeting with a potential technical/security advisor
- Meeting with Ryan RE upcoming deliverables/strategy

**Comment by pstan26** [comment]
Yesterday:
- walk through of software handoff from Tezos
- bounty rules followup with lawyers
- PR outreach with reporters
- Put request in to ES for Berlin event
- meeting with Boris

Today:
- push forward OpSec items
- more emails to Onename users
- Token PDF materials
- few calls

**Comment by shea256** [comment]
Yesterday:

- Handoff meeting with Tezos
- Meeting to discuss the website
- Send out next batch of Onename emails
- Move forward with security reviews
- Follow up with AL

Today:

- Identity verification meeting with Larry and Ken
- Meeting with Muneeb to discuss deliverables and strategy
- Meeting with a potential advisor on key security
- Meeting with a service provider on key security
- Send out next batch of Onename emails

**Comment by kantai** [comment]
Yesterday
* Ship Windows and Linux builds for Browser
* Work on performing social proof checks in the gaia-hub

Today
* New release of core with gaia-hub support, payment key passing
* Meetings with security audits
* Start testing multi-reader storage

**Comment by jackzampolin** [comment]
_yesterday_
- Gaia Hub Deployment
- Integration Tests per push runs (WIP)

_today_
- Onename emails
- Integration tests

**Comment by muneeb** [comment]
Please make sure you add the right persons on your project. @muneeb is my handle and I dont have the remotest idea of who you guys are and what this project is about.
