### ISSUE TITLE
Mon, Sep 25, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/daily-standup#141]
Quick Link: [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**Friday/Saturday/Sunday**_: 
- [x] Review browser design issues and community member responses
- [x] [#403: Worked on update all container classes to work with Bootstrap v4](https://github.com/blockstack/blockstack.org/issues/403)
- [x] [#404: Remove all custom `@media` queries & rule sets](https://github.com/blockstack/blockstack.org/issues/404)
- [x] [#405: Update sticky social share to remove custom media query](https://github.com/blockstack/blockstack.org/issues/405)
- [x] [#406: Update to HTML5 doctype](https://github.com/blockstack/blockstack.org/issues/406)
- [x] [#407 Update to responsive meta-tags](https://github.com/blockstack/blockstack.org/issues/407)
- [x] [token portfolio manager bounty images for email and eventbrite](https://github.com/blockstack/designs/issues/437)
- [x] Took a Sublime Text 3 full day course to increase productivity

_**today**_:
- [ ] Finalize [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [ ] Finalize [#398: Rebuild Token Banner to be an `alert` banner](https://github.com/blockstack/blockstack.org/issues/398)
- [ ] [#400: Update navbar items](https://github.com/blockstack/blockstack.org/issues/400)
- [ ] Work on [new About page design](https://github.com/blockstack/blockstack.org/issues/401)

_**ahead**_:
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] Quick css live design update to to do list app
- [ ] Add grid to `browser-v0.11.sketch` file

Link to today's open source design contributor standup:
- [#443: design standup – Mon, Sep 25, 2017](https://github.com/blockstack/designs/issues/443)

**Comment by yknl** [comment]
**Last week**
- Fix blockstack-browser issues and get it ready for release
- Meetings to sync up on frontend tasks
- Complete implementation of core API use in blockstack-explorer
- Added profile list to explorer address page

**Today**
- Test blockstack-explorer updates
- Start working on blockstack-browser social proof verifications

**Comment by pstan26** [comment]
*Last week*:
- Software handoff with Tezos
- secured bounty rules from lawyers
- finalized eventbrite for bounty (ready to send out tmrw)
- Requested ES for Berlin Event
- finalized Berlin Video
- emailed 30k Onename users
- Got Bill Hessert to agree to create landing page, logo, for app addition
- rounded up security folks for opsec, coinlist, and web property pen testing to begin this week
- uploaded 21 new Blockstack Academy Vids from past meetup


*Today*:
- LaunchSquad project proposal
- Matt Weinstein Mining Whitepaper Audit
- Secure Web Properties
- DDOS service from Cloudflare
- Operational Security
- Browser
- CoinList Website
- Launch bounty program
- Token PDF materials
- Token Video A Roll review

**Comment by jackzampolin** [comment]
_yesterday_
- Onename emails
- Integration test automation
- Build and release process improvement

_today_
- spinning up tests for hard fork
- integration tests

**Comment by kantai** [comment]
*yesterday*
* audit phone calls
* gaia_hub support for social proofs
* gaia_hub support in browser

*today*
* testing integration of multi-reader storage
* looking through hacker1

**Comment by jcnelson** [comment]
Yesterday:

* hard fork testing

Today:

* implement grace period for renewal
* hard fork testing
