### ISSUE TITLE
Tue, Sep 26, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/daily-standup#142]
Quick Link: [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**yesterday**_: 
- [x] Worked with @estermer on [#380: integrate ui from api.onename.com for FAQ section](https://github.com/blockstack/blockstack.org/issues/380)
- [x] Worked on [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [x] Worked on [#398: Rebuild Token Banner to be an `alert` banner](https://github.com/blockstack/blockstack.org/issues/398)
- [x] Worked on [#411: Rebuild navbar to match new Bootstrap v4 navbar structure](https://github.com/blockstack/blockstack.org/issues/411)
- Ran into issues with npm installation that kept reverting back from Bootstrap v4 to old alpha version without knowledge. Would end up resolving issues on both versions.
- Had to go home early and lost quite a bit of the day.

_**today**_:
- [x] [#411: Rebuild navbar to match new Bootstrap v4 navbar structure](https://github.com/blockstack/blockstack.org/issues/411)
- [x] Finalize [#398: Rebuild Token Banner to be an `alert` banner](https://github.com/blockstack/blockstack.org/issues/398)
- [ ] Finalize [#403: Update all container, heading, centering & lead classes to work with Bootstrap v4](https://github.com/blockstack/blockstack.org/issues/403)
- [ ] Finalize [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [ ] [Write up quick paragraph on the v0.17.0 browser design](https://github.com/blockstack/blockstack/blob/master/newsletters/newsletter-09-2017.md)
- [ ] Work on [new About page design](https://github.com/blockstack/blockstack.org/issues/401)
- [ ] Finalize [#380: integrate ui from api.onename.com for FAQ section](https://github.com/blockstack/blockstack.org/issues/380)
- [ ] [#400: Update navbar items](https://github.com/blockstack/blockstack.org/issues/400)

_**ahead**_:
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] Quick css live design update to to do list app
- [ ] Add grid to `browser-v0.11.sketch` file

Link to today's open source design contributor standup:
- [#444: design standup – Tue, Sep 26, 2017](https://github.com/blockstack/designs/issues/444)

**Comment by yknl** [comment]
**Yesterday**
- Test blockstack-explorer updates, fixed issues
- Diagnose & fix issues in blockstack.org site

**Today**
- Remove third-party CDN includes from blockstack.org
- Finish testing + review of blockstack-explorer updates
- Update explorer in production
- Start working on blockstack-browser social proof verifications

**Comment by GinaAbrams** [comment]
Yesterday
-candidates on hold 
-spoke to wifi providers 
-got some lights up 
-Sec ops meeting 
-new domain name transfer 
-Started on company swag website 

Today
-call wifi providers pt. II 
-get company shop better looking 
-get in touch with all printing providers about drop shipping 
-check in with ops sec people (fobs, door) 
-ping Nomad + Ryan and Muneeb about issuing payments in bill.com 
-Inquire about QSEHRA for out of state healthcare

**Comment by larrysalibra** [comment]
Today: 
- Started re-enabling built-in bitcoin wallet. Was able to send regtest bitcoin to the browser wallet.
- Modified browser tests to enforce linter on lint free files
- Proposed a new hard fork feature on the forum
- Sync up with ken & ryan re verifications ux
- Sync up with ryan re onename login issues

Tomorrow: 
- Continue (hopefully finish) in-browser bitcoin wallet

**Comment by kantai** [comment]
Yesterday:
* Start working through HackerOne issues
* Testing setup of multi-reader storage

Today:
* Patch issue Larry discovered in core-regtest while using browser's payment key
* Audit calls
* Continue working through HackerOne issues
* Continue testing of multi-reader storage

**Comment by pstan26** [comment]
Yesterday: 

Today:
LaunchSquad project proposal
Matt Weinstein Mining Whitepaper Audit
Secure Web Properties via cloudflare / godaddy
DDOS service from Cloudflare (getting update)
Operational Security - commences today with Ryan Lackey
Browser -
CoinList Website - approval today
Launch bounty program - launched, just needs to be tweeted
Token PDF materials
Token Video A Roll review - completing
Pen Testing - commences today
Onename emails

**Comment by GinaAbrams** [comment]
Yesterday: 
-Shopify site first draft 
-Got in touch w ( / in process of getting in touch w) swag providers 
-Internet calls (spectrum refund, wireless quote) 
-bill.com clean up / reach out to Brandon
-Edits to application for keyvalues.io 

Today: 
-Finalize updates to keyvalues.io 
-Reach out to more avenues we can be on for hiring marketing 
-Finalize swag shop
-Check in with Bill 
-Help w any ops sec stuff possible

**Comment by larrysalibra** [comment]
Today:
* Fixed a some legacy sign in issues with Onename.
* Tested name exports

Tonight/Tomorrow:
* Review explorer pull request
* Continue on browser bitcoin wallet & test aaron's fix for core's wallet issue

**Comment by kantai** [comment]
Yesterday:
* Pen Testing kickoff
* HackerOne issues
* Testing and patching multi-reader storage issues

Today:
* More multi-reader storage testing (with the gaia_hub combo)

**Comment by jcnelson** [comment]
Yesterday:

* implement renewal grace period in hard fork
* add tests for it

Today:

* More testing for the hard fork

**Comment by jackzampolin** [comment]
_yesterday_
- spinning up tests for hard fork
- integration tests
- Integration test automation

_today_
- Helping with hardfork testing
- Explorer deployment strategies

**Comment by pstan26** [comment]
y'day
- Call with angellist (introing then to security audit)
- Call with cloudflare (ryan lackey pointed us toward cheaper domain hosting)
- Tax call with John 
- Followed up with a app developers looking to build applications
- Added comments to token video 

t'day
- Nomad financial
- Arranging security audits for browser and core 
- Legal language about speakers not supporting token
- Finalize Newsletter for Friday(?)
