### ISSUE TITLE
Wed, Sep 27, 2017

### ISSUE THREAD

**Issue by shea256** [blockstack/daily-standup#143]
Yesterday:

- Meeting with Larry to discuss Onename deliverables
- Meeting with the frontend team to discuss browser verifications
- Documentation of more details for the wallet models for Bitcoin and Ethereum
- Legal calls along with Muneeb + discussions

Today:

- Revisit the overall timeline to make sure we can fit everything in.
- Work through browser stories and figure out what needs to get done there.
- Chat with AngelList to review the upcoming work and sync up on their timelines.

**Comment by yknl** [comment]
**Yesterday**
- Replace third-party CDN includes from blockstack.org with npm + gulp
- Frontend sync on browser social proof verification UX
- Continue testing of blockstack-explorer updates
- Document explorer setup procedure to enable docker deploy

**Today**
- Work with jack to setup docker deploy for explorer
- Work on design of social proof verification UX

**Comment by pstan26** [comment]
*Yesterday*
- arranged time to go over DDoS and domain securing service from Cloudflare (getting update)
-Operational Security - commenced today with Ryan Lackey
- Signed contract to audit AngelList Website - commenced with Josh need to put in touch
- Launched Bounty program with 
- Signed contract for Penetration Testing - commenced with Danial
- Drafted Newsletter

*Today*
- LaunchSquad project proposal
- Token PDF materials
- Token Video A Roll review - completing
- confirm auditor to take on Browser and core 
- Sign special speaker contract
- Secure Web Properties via cloudflare / godaddy
- Sending out more Onename emails

**Comment by larrysalibra** [comment]
Today:
* Fixed a some legacy sign in issues with Onename.
* Tested name exports

Tonight/Tomorrow:
* Review explorer pull request
* Continue on browser bitcoin wallet & test aaron's fix for core's wallet issue

**Comment by guylepage3** [comment]
Quick Link: [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**yesterday**_: 
- [x] Worked with @estermer on [#380: integrate ui from api.onename.com for FAQ section](https://github.com/blockstack/blockstack.org/issues/380)
- [x] Worked with @estermer on [#413: Integrate ui from api.onename.com to Docs page](https://github.com/blockstack/blockstack.org/issues/413)
- [x] [#411: Rebuild navbar to match new Bootstrap v4 navbar structure](https://github.com/blockstack/blockstack.org/issues/411)
  - Ran into issues with npm installation that kept reverting back from Bootstrap v4 to old alpha version without knowledge. Would end up resolving issues on both versions.
- [x] Finalize [#398: Rebuild Token Banner to be an `alert` banner](https://github.com/blockstack/blockstack.org/issues/398)
- [x] Started [#416: Build UI placeholder image for Reason TV video home page](https://github.com/blockstack/blockstack.org/issues/416)

_**today**_:
- [x] Finalize [#403: Update all container, heading, centering & lead classes to work with Bootstrap v4](https://github.com/blockstack/blockstack.org/issues/403)
- [x] Finalize [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [x] [#418: Add Windows Browser link to install page](https://github.com/blockstack/blockstack.org/issues/418)
- [x] [#400: Update navbar items](https://github.com/blockstack/blockstack.org/issues/400)
- [ ] [#401: Update About page](https://github.com/blockstack/blockstack.org/issues/401)
- [ ] Finalize [#416: Build UI placeholder image for Reason TV video home page](https://github.com/blockstack/blockstack.org/issues/416)
- [ ] Finalize [#380: integrate ui from api.onename.com for FAQ section](https://github.com/blockstack/blockstack.org/issues/380)
- [ ] [Write up quick paragraph on the v0.17.0 browser design](https://github.com/blockstack/blockstack/blob/master/newsletters/newsletter-09-2017.md)

_**ahead**_:
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] Quick css live design update to to do list app
- [ ] Add grid to `browser-v0.11.sketch` file

Link to today's open source design contributor standup:
- [#445: design standup – Wed, Sep 27, 2017](https://github.com/blockstack/designs/issues/445)

**Comment by jcnelson** [comment]
Yesterday:

* integration tests on hard fork

Today:

* integration tests on hard fork
* get multi-reader storage working

**Comment by jackzampolin** [comment]
_yesterday_
- Helping with hardfork testing
- Explorer deployment strategies
- v2 API deployment work
- Call with cloudflare about DDoS protection for blockstack.org

_today_
- Multireader testing
- Docker Compose setup for the v2 API

**Comment by GinaAbrams** [comment]
Tues: 
- Got company shop preliminary set up 
- Calls w WiFi 
- Ops: finance / check in with operational security stuff 
- edits on keyvalues.io submission 
- On boarding playbook 

Wed: 
- Call w Amplifier 
- Continue updates and edits on Keyvalues.io 
- Edits to onboarding playbook 
- Sync w & meet candidate for Bill

**Comment by muneeb-ali** [comment]
Wed: 
- Meeting with AngelList
- Work on drafts of a new type of asset purchase agreements
- Brainstorming session with lawyers to figure out details of legal framework
- Send feedback on asset valuation report
