### ISSUE TITLE
Thu, Sep 28, 2017

### ISSUE THREAD

**Issue by shea256** [blockstack/daily-standup#144]
Yesterday:

- Worked through browser stories, wrote comments, and kept everything on track.
- Had a meeting with a security consultant to work through key management
- Had some calls and conversations with Muneeb about legal work
- Had a meeting with AngelList to review the upcoming work and sync up on their timelines.
- Revisited the overall timeline and made adjustments

**Comment by shea256** [comment]
Today:

- Signatures
- Website
- Product
- Security

**Comment by larrysalibra** [comment]
Today:
* reviewed & feedback on explorer
* tested legacy login and legacy transfer on onename. good to ship

Tonight:
* gaia hub onboarding mock ups. 
* name ux stuff

Tonight/Tomorrow: 
* browser bitcoin wallet
* update UI for gaiahub

**Comment by yknl** [comment]
**Yesterday**
- Work on design and implementation of social proof verification UX
- Help setup docker deploy for explorer

**Today**
- Address explorer issues from larry's feedback on the PR
- Fix bug in browser, where profile isn't displayed when logging into apps
- Work on implementation of new social proof verification UX

**Comment by jcnelson** [comment]
Yesterday:

* get multi-reader storage working
* integration tests for register/update via the RESTful API
* more integration tests for the hard fork

Today:

* finish integration tests for the hard fork
* begin spinning up nodes to verify that they reach consensus with 0.14.x

**Comment by jackzampolin** [comment]
_yesterday_
- Multireader testing
- Docker Compose setup for the v2 API

_today_
- Docker Compose setup for the v2 API
- Looking into replacement for the insight api
- Multireader testing

**Comment by GinaAbrams** [comment]
Wed: 
- Call w Amplifier (can integrate w 3rd parties for drop shipping) 
- Continue updates and edits on Keyvalues.io 
- Edits to onboarding playbook 
- Sync w & meet candidate for Bill 

Today: 
- Research other platforms to connect to other than Keyvalues 
- Meeting with finance dept for bill.com 
- Interview with Bill 
- See how we can connect talent for apps outside of slack

**Comment by guylepage3** [comment]
Quick Link: [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**yesterday**_: 
- [x] Finalize [#403: Update all container, heading, centering & lead classes to work with Bootstrap v4](https://github.com/blockstack/blockstack.org/issues/403)
- [x] Worked on [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [x] [#418: Add Windows Browser link to install page](https://github.com/blockstack/blockstack.org/issues/418)
- [x] [#400: Update navbar items](https://github.com/blockstack/blockstack.org/issues/400)

_**today**_:
- [ ] Work on [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [ ] Finalize [#416: Build UI placeholder image for Reason TV video home page](https://github.com/blockstack/blockstack.org/issues/416)
- [ ] [#401: Update About page](https://github.com/blockstack/blockstack.org/issues/401)
- [ ] Finalize [#380: integrate ui from api.onename.com for FAQ section](https://github.com/blockstack/blockstack.org/issues/380)
- [ ] [Write up quick paragraph on the v0.17.0 browser design](https://github.com/blockstack/blockstack/blob/master/newsletters/newsletter-09-2017.md)
- [ ] Go through entire site and make sure sections are consistent

_**ahead**_:
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] Quick css live design update to to do list app
- [ ] Add grid to `browser-v0.11.sketch` file

Link to today's open source design contributor standup:
- [#446: design standup – Thu, Sep 28, 2017](https://github.com/blockstack/designs/issues/446)

**Comment by guylepage3** [comment]
Link to today's open source design contributor standup:
- [#446: design standup – Thu, Sep 28, 2017](https://github.com/blockstack/designs/issues/446)

**Comment by kantai** [comment]
Yesterday:
* Multi-reader testing
* Security audit work

Today:
* Testing gaia hub support
* Hacking on a name-recovery script
* Assisting with hard-fork testing as needed

**Comment by muneeb-ali** [comment]
Thur:
- Calls with lawyers RE PBC tasks and board consents
- Work with lawyers on checklist of upcoming tasks
- Got feedback on first half of the whitepaper and incorporated it
