### ISSUE TITLE
Friday, September 29, 2017

### ISSUE THREAD

**Issue by kantai** [blockstack/daily-standup#145]
Yesterday
* Testing and then separating branch for multi-reader storage
* Testing on Gaia Hub
* Bugfixing in Windows Installer
* Working on a recovery script for older backup phrases

Today
* Will be in-flight during normal stand-up
* Assist in testing hard-fork
* More Windows Installer debugging

**Comment by guylepage3** [comment]
Quick Link: [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**yesterday**_: 
- [x] Worked on [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [x] [#401: Update About page](https://github.com/blockstack/blockstack.org/issues/401)
- [x] Finalize [#380: integrate ui from api.onename.com for FAQ section](https://github.com/blockstack/blockstack.org/issues/380)
- [x] Review, merge and touch-up [#417: Integrate ui from api.onename.com to Docs page](https://github.com/blockstack/blockstack.org/pull/417)
- [x] Touched and rebuilt structure on all pages/sections of blockstack.org other than;
  - sign-up
  - funding
  - press
  - press pre-footer
  - intro
  - careers
  - career link
  - 404 page
  - See components and pages list here [›› Complete list](https://github.com/blockstack/blockstack.org/issues/399)

_**today**_:
- [x] Finalize [#415: Live design new footer](https://github.com/blockstack/blockstack.org/issues/415)
- [x] [#424: Restructure funding page](https://github.com/blockstack/blockstack.org/issues/424)
- [x] [#427: Update home page layout](https://github.com/blockstack/blockstack.org/issues/427)
- [ ] Finalize [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [ ] Finalize [#401: Update About page](https://github.com/blockstack/blockstack.org/issues/401)
- [ ] [#421: Build new privacy policy page](https://github.com/blockstack/blockstack.org/issues/421)
- [ ] Finalize [#416: Build UI placeholder image for Reason TV video home page](https://github.com/blockstack/blockstack.org/issues/416)
- [ ] [#408: Build new Press Page](https://github.com/blockstack/blockstack.org/issues/408)
- [ ] [#425: Site audit for consistency and continuity](https://github.com/blockstack/blockstack.org/issues/425)

_**ahead**_:
- [ ] [#426: Add more links and content to social share sticky footer of blockstack.org](https://github.com/blockstack/blockstack.org/issues/426)
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] Quick css live design update to to do list app
- [ ] Add grid to `browser-v0.11.sketch` file

Link to today's open source design contributor standup:
- [#447: design standup – Fri, Sep 29, 2017](https://github.com/blockstack/designs/issues/447)

**Comment by yknl** [comment]
**Yesterday**
- Address explorer issues from larry's feedback on the PR
- Fix bug in browser, where profile isn't displayed when logging into apps
- Work on implementation of new social proof verification UX

**Today**
- Work on implementation of new social proof verification UX

**Comment by shea256** [comment]
Yesterday:

- Chased signatures down for the PBC update
- Legal call
- Continued on AngelList work
- Browser product management

Today:

- Follow up with security deliverables
- Work on token purchase agreements
- Meeting w/ Muneeb

**Comment by pstan26** [comment]
Yesterday:
Sent LaunchSquad an updated proposal for working with us
Sent out Blockstack Newsletter
Went over some engagement strategy with Xan for Bounty
Set up account on F6S 
Sent asks back to speaker for promotion of event

Today:
Call with developer building token portfolio app
Evangelist call 
Security confirmation for Browser and Core
Call with Aaron on Token video

**Comment by GinaAbrams** [comment]
Yesterday: 
- Fully up and running on bill.com  
- Connected to Keyvalues, Built in NYC (made an account then we actually have one already) alleywatch 
- Interview with Bill / additional candidate for him 
- Connected with Xan / Pat and intro look of Hubspot
- Pinged lawyers/internet co 

Today: 
- Sign lever contract / get onboarded
- Show rest of team keyvalues page 
- Quick meeting with Eden (YC co) 
- Research additional channels of branding we can do

**Comment by muneeb-ali** [comment]
Fri:
- Meeting with Albert & Ryan.
- Work with lawyers to finalize token purchase agreements and give feedback

**Comment by jackzampolin** [comment]
_yesterday_
- Blockstack V2 API Deployment
- Insight API re-implementation planning

_today_
- Blockstack V2 API Deployment
- Talk to developers about building on Blockstack
- Catch up on emails/planning
- Work on reimplementing the Insight API
