### ISSUE TITLE
Tue, Oct 3, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/daily-standup#147]
Quick Link: [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**yesterday**_: 
- [x] Weekly scrum
- [x] Frontend meeting
- [x] [#430: Live design new dropdown menu](https://github.com/blockstack/blockstack.org/issues/430) on blockstack.org
- [x] [#450: Design new placeholder image for blockstack.org home page video](https://github.com/blockstack/designs/issues/450)
- [x] Had issues with the [#416: Build UI placeholder image for Reason TV video home page](https://github.com/blockstack/blockstack.org/issues/416). Had to pass off to @yknl.

_**today**_:
- [x] Front-end meeting
- [x] [#453: Quick design of new "Initial Profile Landing View"](https://github.com/blockstack/designs/issues/453)
- [x] Created Sketch license key for @yknl 
- [x] [#431: Resolve mobile navbar dropdown](https://github.com/blockstack/blockstack.org/issues/431) on blockstack.org
- [ ] [#842: Create new frame and background for browser](https://github.com/blockstack/blockstack-browser/issues/842)
- [ ] Finalize [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [ ] Finalize [#401: Update About page](https://github.com/blockstack/blockstack.org/issues/401)
- [ ] [#421: Build new privacy policy page](https://github.com/blockstack/blockstack.org/issues/421)
- [ ] [#408: Build new Press Page](https://github.com/blockstack/blockstack.org/issues/408)
- [ ] [#429: Update illustrations. Fonts need outlining on blockstack.org](https://github.com/blockstack/blockstack.org/issues/429)
- [ ] [#425: Site audit for consistency and continuity](https://github.com/blockstack/blockstack.org/issues/425)
- [ ] [#454: Resize token portfolio bounty graphic](https://github.com/blockstack/designs/issues/454)
- [ ] [#815: Wallet placeholders values look like real inputs](https://github.com/blockstack/blockstack-browser/issues/815#event-1274504195)

_**ahead**_:
- [ ] [#452: Design CoinList UI](https://github.com/blockstack/designs/issues/452)
- [ ] [#426: Add more links and content to social share sticky footer of blockstack.org](https://github.com/blockstack/blockstack.org/issues/426)
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] Quick css live design update to to do list app
- [ ] Add grid to `browser-v0.11.sketch` file

Link to today's open source design contributor standup:
- [#451: design standup – Tue, Oct 3, 2017](https://github.com/blockstack/designs/issues/451)

**Comment by kantai** [comment]
*Yesterday*:
- Lecture on Blockstack for mfreed's course
- Start work on adding client-side encryption to `blockstack.js`
- Battle a DoS vector on core.blockstack.org

*Today*:
- Finish up client-side encryption in `blockstack.js`
- Start work on Onename Transfers
- Call with Pentesters

**Comment by yknl** [comment]
**Yesterday**
- Frontend sync up
- Work on new social proof verification in browser
- Add ability to use custom preview images on blockstack.org videos

**Today**
- Work on new social proof verification in browser
- Get new explorer version up and running

**Comment by larrysalibra** [comment]
Today:
* Finished the changes to use browser wallet key instead of core wallet key. This means your funds are backed up as long as you keep you 12 word identity key safe!
* Front end sync up re user testing UX feedback

Tomorrow:
* Name UX
* On-boarding & storage setting changes
* Other UX issues

**Comment by muneeb-ali** [comment]
Today:
- Prepared a check-list of all upcoming items for our team of lawyers
- Followed up on legal tasks and sent out the details some folks were waiting for 
- Caught up on organizing our token distribution tasks
- Work on whitepaper at night
- Sorted out SF travel for the week of 10/16

**Comment by shea256** [comment]
Tuesday:

- Meeting with video team to discuss video production
- Frontend meeting
- Wrote up video story notes
- Planned out tasks for the upcoming timeline
- Reviewed the third key solutions document that Aaron put together and followed up with them on the next meeting
- Fixed of the navbar links on the website

**Comment by jcnelson** [comment]
Yesterday:

* work on hard fork features and testing

Today:

* work on hard fork features and testing
* add expiry date to v2 namespace fee capture

**Comment by jackzampolin** [comment]
_yesterday_
- Meetings with Developers building on Blockstack (Misthos, Dovetail, Prop4Crops)
- Blockstack V2 API Deployment

_today_
- Meetings with Developers building on Blockstack (Misthos, Ryan)
- Start spinning up array of v2 core nodes
