### ISSUE TITLE
Wed, Oct 4, 2017

### ISSUE THREAD

**Issue by shea256** [blockstack/daily-standup#148]
Today:

- Video editing day with Optic Sky
- Follow up on legal and operations tasks

**Comment by yknl** [comment]
**Yesterday**
- Frontend meeting
- Work on new social proof verification in browser
- Get new explorer version up and running @ explorer.blockstack.org

**Today**
- Work on browser social proof verifications
- Browser improvements for release https://github.com/blockstack/blockstack-browser/issues/844

**Comment by GinaAbrams** [comment]
Yesterday: 
-Meeting w Eden (office management market place, YC company)
-Implementation call with Lever 
-AngelList app -> lever candidate creation 
-NJ office space research 
-Financial info for one of our investors 

Today: 
-Final draft KeyValues 
-Return lights / desks (small ones and damaged larger) 
-Order TV monitor for new conference room 
-Set up UPS mailbox 
-Lock people are coming in later this PM to install 
-Finalize ecommerce store 
-Integrating with Lever

**Comment by kantai** [comment]
*Yesterday*
- Adding encryption support to `blockstack.js`
- Pentest Meeting
- Cleaning up the blockstack-core/api endpoints (`/v2/users` -> `/v1/users`, remove dead endpoints)
- Sync up on Onename Transfer Infrastructure

*Today*
- Poking around on Onename Transfer Infrastructure
- Sync on Gaia Hub tasks

**Comment by jcnelson** [comment]
Yesterday:

* confirmed 0.17 stays in consensus with 0.14
* work on hard fork features and testing

Today:

* upgrade infrastructure to hard fork (bitcoin 0.15, snapshot server and nodes to 0.17)
* coordinate with muneeb on registrar upgrade

**Comment by larrysalibra** [comment]
Today/Yesterday 
* User testing ux feedback meeting
* Finished browser bitcoin wallet
* Synced up with via video James for Blockstack Melbourne meetup
* Finished gaia storage hub integration in browser
* Wallet ux improvements
* Finished a number of UX issues from the earlier meeting

Remaining Today:
* Name UX
* Sync up with @kantai about transfer process requirements

Tomorrow:
* Prep for Blockstack Melbourne meetup
* Present at Blockstack Melbourne meetup
* Update browser to hard fork core
* Only persist necessary state in browser 
* Persist profiles for nameless IDs
* Refactoring profile settings to be core node based instead of url based
* Review Blockstack.js encryption PR
* Review on-boarding flow with transfers in mind.

**Comment by guylepage3** [comment]
Quick Link: [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**yesterday**_: 
- [x] Front-end meeting
- [x] [#453: Quick design of new "Initial Profile Landing View"](https://github.com/blockstack/designs/issues/453)
- [x] Created Sketch license key for @yknl 
- [x] [#431: Resolve mobile navbar dropdown](https://github.com/blockstack/blockstack.org/issues/431) on blockstack.org

_**today**_:
- [x] Blockstack.org meeting for new content
- [x] [#456: Create quick brand banner](https://github.com/blockstack/designs/issues/456)
- [x] Review browser issues
- [x] [#432: Resolve blockstack.org breakages](https://github.com/blockstack/blockstack.org/issues/432) that occurred during lsat night's merge
- [x] [#455: Design new frame and background for browser](https://github.com/blockstack/designs/issues/455)
- [ ] [#433: Live design new multi-video player for all 4 views](https://github.com/blockstack/blockstack.org/issues/433)
- [ ] [#435: Live design new home page whitepaper section](https://github.com/blockstack/blockstack.org/issues/435)
- [ ] [#458: Design two PDF cover pages for token whitepapers](https://github.com/blockstack/designs/issues/458)
- [ ] [#459: Design two new whitepaper icons](https://github.com/blockstack/designs/issues/459)
- [ ] Finalize [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [ ] Finalize [#401: Update About page](https://github.com/blockstack/blockstack.org/issues/401)
- [ ] [#408: Build new Press Page](https://github.com/blockstack/blockstack.org/issues/408)
- [ ] [#421: Build new privacy policy page](https://github.com/blockstack/blockstack.org/issues/421)
- [ ] [#429: Update illustrations. Fonts need outlining on blockstack.org](https://github.com/blockstack/blockstack.org/issues/429)
- [ ] [#842: Create new frame and background for browser](https://github.com/blockstack/blockstack-browser/issues/842)
- [ ] [#425: Site audit for consistency and continuity](https://github.com/blockstack/blockstack.org/issues/425)

_**ahead**_:
- [ ] [#414: Add Explorer Tutorial to /tutorials page](https://github.com/blockstack/blockstack.org/issues/414)
- [ ] [#852: Add section with documentation links](https://github.com/blockstack/blockstack-browser/issues/852)
- [ ] [#847: Clean up 404 page](https://github.com/blockstack/blockstack-browser/issues/847)
- [ ] [#815: Wallet placeholders values look like real inputs](https://github.com/blockstack/blockstack-browser/issues/815#event-1274504195)
- [ ] [#454: Resize token portfolio bounty graphic](https://github.com/blockstack/designs/issues/454)
- [ ] [#452: Design CoinList UI](https://github.com/blockstack/designs/issues/452)
- [ ] [#426: Add more links and content to social share sticky footer of blockstack.org](https://github.com/blockstack/blockstack.org/issues/426)
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] Quick css live design update to to do list app
- [ ] Add grid to `browser-v0.11.sketch` file

Link to today's open source design contributor standup:
- [#457: design standup – Wed, Oct 4, 2017](https://github.com/blockstack/designs/issues/457)

**Comment by muneeb-ali** [comment]
Wed:
- Worked with lawyers on what items need to be delivered this week and cleared roadblocks
- Looked into requirements/details for 83b elections for team/investors
- Started a Google form for getting details from potential investors and got it reviewed by securities lawyers 
- Email catch up, especially getting back to potential investors
- Worked with Aaron to handoff some Onename registrar items
- Feedback on upcoming video
- Resumed work on the whitepaper at night
- Meeting with Guy on blockstack.org website updates

**Comment by jackzampolin** [comment]
_yesterday_
- Meetings with Developers building on Blockstack (Misthos, Ryan)
- Start spinning up array of v2 core nodes

_today_
- Worked on building out array of v2 core nodes
- Worked on getting index creation and reindexing in docker
- Meetings with Developers building on Blockstack (Misthos)

**Comment by jcnelson** [comment]
Yesterday:

* added expiry to fee capture period for v2 namespaces
* added tests for the above

Today:

* migrate bitcoin fleet
* migrate test nodes
* add tests for snapshot server
* upgrade snapshot server
