### ISSUE TITLE
Fri, Oct 6, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/daily-standup#150]
Quick Link: [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**yesterday**_: 
- [x] Provide edits to [#455: Design new "temporary" frame and background for browser](https://github.com/blockstack/designs/issues/455)
- [x] Meeting `#4` for blockstack.org w/ @shea256 
- [x] Finalize [#433: Live design new multi-video player for all 4 views](https://github.com/blockstack/blockstack.org/issues/433)
- [x] [#461: Locate, extract & convert to SVG vector logos for WSJ, MIT, Observer](https://github.com/blockstack/designs/issues/461)
- [x] [#438: Live design new press section on home page](https://github.com/blockstack/blockstack.org/issues/438)
- [x] [#435: Live design new home page whitepaper section](https://github.com/blockstack/blockstack.org/issues/435)
- [x] Worked on a couple iterations of [#459: Design two new whitepaper icons](https://github.com/blockstack/designs/issues/459)

_**today**_:
- [x] [#458: Design two PDF cover pages for token whitepapers](https://github.com/blockstack/designs/issues/458)
- [x] Finalize [#459: Design two new whitepaper icons](https://github.com/blockstack/designs/issues/459)
- [x] [#463: Design hard fork blog post image](https://github.com/blockstack/designs/issues/463)
- [ ] ›› [#437: Remove“Token banner” replace w/blue “pill” navbar btn](https://github.com/blockstack/blockstack.org/issues/437)
- [ ] [#436: Remove "Get Updates" btn & place form on bottom of page](https://github.com/blockstack/blockstack.org/issues/436)
- [ ] [#429: Update illustrations. Fonts need outlining on blockstack.org](https://github.com/blockstack/blockstack.org/issues/429)

_**ahead**_:
- [ ] [#408: Build new Press Page](https://github.com/blockstack/blockstack.org/issues/408)
- [ ] Finalize [#401: Update About page](https://github.com/blockstack/blockstack.org/issues/401)
- [ ] Finalize [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [ ] [#421: Build new privacy policy page](https://github.com/blockstack/blockstack.org/issues/421)
- [ ] [#425: Site audit for consistency and continuity](https://github.com/blockstack/blockstack.org/issues/425)
- [ ] [#842: Create new frame and background for browser](https://github.com/blockstack/blockstack-browser/issues/842)
- [ ] [#414: Add Explorer Tutorial to /tutorials page](https://github.com/blockstack/blockstack.org/issues/414)
- [ ] [#852: Add section with documentation links](https://github.com/blockstack/blockstack-browser/issues/852)
- [ ] [#847: Clean up 404 page](https://github.com/blockstack/blockstack-browser/issues/847)
- [ ] [#815: Wallet placeholders values look like real inputs](https://github.com/blockstack/blockstack-browser/issues/815#event-1274504195)
- [ ] [#454: Resize token portfolio bounty graphic](https://github.com/blockstack/designs/issues/454)
- [ ] [#452: Design CoinList UI](https://github.com/blockstack/designs/issues/452)
- [ ] [#426: Add more links and content to social share sticky footer of blockstack.org](https://github.com/blockstack/blockstack.org/issues/426)
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] Quick css live design update to to do list app
- [ ] Add grid to `browser-v0.11.sketch` file

Link to today's open source design contributor standup:
- [#462: design standup – Fri, Oct 6, 2017](https://github.com/blockstack/designs/issues/462)

**Comment by yknl** [comment]
**Yesterday**
- Wrap up and test social proof verifications on browser
- Video component on blockstack.org

**Today**
- Wrap up and test social proof verifications in browser 
- Clean up name purchase view in browser
- Add profile search to browser
- Get browser ready for release

**Comment by kantai** [comment]
*Yesterday*
 - Assist in testing and deploying the hard fork
 - Work on having onename transfers use the v17 renew-update-transfer operation

*Today*
 - Fix price calculation in `blockstack-core` so that it more accurately reflects the actual price
 - More onename transfer work -- this is pretty much set to test on production, but will require a little bit of careful treatment

**Comment by jackzampolin** [comment]
_yesterday_
- Meetings with developers
- Inaugural Blockstack Office Hours for Bounty participants
- Look into issues with Integration Test Bot (All power to the bots)
- OpSec meeting for the tokensale
- Working on getting array of core nodes operational

_today_
- Meetings with developers
- Gaia hub changes and deployment
- Spin up v0.17 core node for @muneeb-ali 
- Core V2 api deployment planning
- Insight API hacking

**Comment by jcnelson** [comment]
Yesterday:

* Blockstack New Year!
* Update CLI worksheets for creating namespaces to reflect new features
* Update node.blockstack.org nodes to 0.17
* Package and merge all hard fork code to `master` in the relevant repos
* Push 0.17 to pypi
* monitor hard fork execution.  Divergence happened at 488541, when Larry registered `happyforkday.id` using the new `NAME_REGISTRATION/NAME_UPDATE` combined transaction.

**Comment by shea256** [comment]
Today:

- Called Josh about security reviews
- Met with Gina about task management
- Met with Guy about blockstack.org
- Followed up with Juliano about security reviews
- Reached out to a lawyer friend about upcoming work
- Coordinated with lawyers about upcoming deliverables
- Met with Muneeb about our upcoming tlmeline
- Coordinated around content for video production
- Wrote a new edit of the hard fork blog post

**Comment by muneeb-ali** [comment]
Fri:
- Work with lawyers on purchase agreements
- Work with lawyers on offering docs
- Finished whitepaper draft v2 and shared with team (main task)
- Meeting with Ryan RE upcoming deliverables
