### ISSUE TITLE
Tue, Oct 10, 2017

### ISSUE THREAD

**Issue by pstan26** [blockstack/daily-standup#152]
Monday:
- sync with event planner to move Berlin date (coordinated next steps for quick turnaround before announcement
- met with "Global Content Platform" creator... very strong lead for funding
- Got two contractors to review whitepaper
- worked on bounty announcement and funnel optimization

Today:
- [ ] PR drafting and outreach to WSJ and NYT on token
- [ ] Naval agreement (w/ dis) 
- [ ] Add disclaimer about non-endorsement of token to materials
- [ ] Get reddit engagement up
- [ ] Followup with Launchsquad
- [ ] Get investor lists from summit + token email list for next week's meetings
- [ ] Meeting with Gab.ai, Open Ocean VC, Penetration testing sync, Zach Valenti on meetup growth flywheel
- [ ] Schedule some user testing this week (current instructions / software for getting started with Blockstack needs some work (the recent new updates to Core and Browser might be a reason here) and new users are not able to easily get up and running)
- [x] Request bounty $ from albert

**Comment by jackzampolin** [comment]
_Yesterday_:
- Taught @mfreed's Princeton Class about building Blockstack apps.
- Team meeting
- Forum question answering
- /r/blockstack question answering
- Updating documentation on blockstack-todos
- Talked with @pstan26 about growing reddit #s 
- Worked on getting some `help-wanted` issues on `blockstack-browser`

_Today_:
- Security meetings
- Getting some `help-wanted` issues on `blockstack-browser` and `blockstack-core`
- Forum Answers
- /r/blockstack answers
- Testing Onename transfers
- Work on testing blog post

**Comment by yknl** [comment]
**Yesterday**
- Team meeting, frontend meeting
- Review merge in pull request for browser
- Browser profile changes:
  Show bitcoin address and domain name
  Auto-generate hacker news proof url
  Fix cursor in social account input
  Verification background transition

**Today**
- Improve pending status indication in social proofs
- Design and build profile progress indicator
- Update nav bar and add labels

**Comment by guylepage3** [comment]
Quick Link: [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**yesterday**_: 
- [x] [#436: Remove "Get Updates" btn & place form on bottom of page](https://github.com/blockstack/blockstack.org/issues/436)
- [x] [#226: Live design sign-up form page](https://github.com/blockstack/blockstack.org/issues/226)
- [x] [#466: Design new Home and Wallet icons for browser](https://github.com/blockstack/designs/issues/466)
- [x] Major update to whitepaper section on home page of blockstack.org
- [x] [#877: Place new Home and Wallet Icons](https://github.com/blockstack/blockstack-browser/issues/877)
- [x] Worked on [#465: Design active state icons for browser](https://github.com/blockstack/designs/issues/465)

_**today**_:
- [x] Finalize [#465: Design active state icons for browser](https://github.com/blockstack/designs/issues/465)
- [x] [#468: New browser profile design](https://github.com/blockstack/designs/issues/468) from Frontend meeting
- [x] [#429: Update illustrations. Fonts need outlining on blockstack.org](https://github.com/blockstack/blockstack.org/issues/429)
- [ ] ›› [#408: Build new Press Page](https://github.com/blockstack/blockstack.org/issues/408)
- [ ] [#842: Create new frame and background for browser](https://github.com/blockstack/blockstack-browser/issues/842)
- [ ] [#887: Add "DotPodcast" app to app store](https://github.com/blockstack/blockstack-browser/issues/887)
- [ ] [#847: Clean up 404 page](https://github.com/blockstack/blockstack-browser/issues/847)
- [ ] Finalize [#401: Update About page](https://github.com/blockstack/blockstack.org/issues/401)

_**ahead**_:
- [ ] Finalize [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [ ] [#421: Build new privacy policy page](https://github.com/blockstack/blockstack.org/issues/421)
- [ ] [#425: Site audit for consistency and continuity](https://github.com/blockstack/blockstack.org/issues/425)
- [ ] [#414: Add Explorer Tutorial to /tutorials page](https://github.com/blockstack/blockstack.org/issues/414)
- [ ] [#852: Add section with documentation links](https://github.com/blockstack/blockstack-browser/issues/852)
- [ ] [#815: Wallet placeholders values look like real inputs](https://github.com/blockstack/blockstack-browser/issues/815#event-1274504195)
- [ ] [#454: Resize token portfolio bounty graphic](https://github.com/blockstack/designs/issues/454)
- [ ] [#452: Design CoinList UI](https://github.com/blockstack/designs/issues/452)
- [ ] [#426: Add more links and content to social share sticky footer of blockstack.org](https://github.com/blockstack/blockstack.org/issues/426)
- [ ] Resolve UI breakages on onename.com in Safari
- [ ] Quick css live design update to to do list app
- [ ] Add grid to `browser-v0.18.sketch` file

Link to today's open source design contributor standup:
- [#467: design standup – Tue, Oct 10, 2017](https://github.com/blockstack/designs/issues/467)

**Comment by kantai** [comment]
Yesterday:
- more work on the onename transfer
- squashing config bugs in the latest core release

Today:
- spin up the new onename transfer-renew-update path (should have the first successful name transfered soon!)
- updates with pentesters

**Comment by shea256** [comment]
Today:

- Had a frontend meeting to review the profile completion UX
- Wrote a draft of our Q3 investor update
- Pushed the updates to blockstack.org
- Task managed all of our token distribution tasks
- Had a call with Cooley about legal work
- Had a call with Olaf about the whitepaper
- Synced up with AngelList on upcoming timelines and deliverables
- Synced up with Larry on the deployment process for onename.com
- Created lists of investors for Muneeb and I to reach out to
- Whipped up a quick web page for Blockstack Token LLC / blockstack.com

**Comment by jcnelson** [comment]
Yesterday:

* work on name renewals

Today: 

* hardening
* security countermeasures
* fixing integration tests to be more predictable

**Comment by muneeb-ali** [comment]
Tue: 
- Wrote new sections for the token whitepaper
- Sent out new versions of token whitepaper to external reviewers 
- Call with lawyers RE 83b elections 
- Calls RE feedback on token whitepaper 
- Worked with Aaron to push registrar updates for transfers live
