### ISSUE TITLE
Wed, Oct 11, 2017

### ISSUE THREAD

**Issue by pstan26** [blockstack/daily-standup#153]
Monday:
Request bounty $ from albert he's in for $10k
Call with Gab.ai
User testing with Hunter from Props4Crops
Met with Bill Hessert
Zach valenti on meetup strategy

Today:
Work on investor deck content
 PR drafting and outreach to WSJ and NYT on token
 Prepare email to go to OneName users
 Add disclaimer about non-endorsement of token to materials
 Get reddit engagement up
 Followup with Launchsquad
 Get investor lists from summit + token email list for next week's meetings
 Followup on more some user testing this week (current instructions / software for getting started with Blockstack needs some work (the recent new updates to Core and Browser might be a reason here) and new users are not able to easily get up and running)
BD for getting token
-coinbase broker

**Comment by yknl** [comment]
**Yesterday**
- Frontend meeting
- Edit verification transition improvements + other browser UI issues
- Work on user trust level system in browser

**Today**
- Work on user trust level system in browser
- Clean up other outstanding browser issues

**Comment by kantai** [comment]
*Yesterday*
- Onename transfer backend work
- Assist in hotfixes on blockstack-core

*Today*
- Onename transfer backend should also copy over profiles

**Comment by shea256** [comment]
Today:

- Whitepaper blog post
- Updates to blockstack.org
- Browser release review and requirements
- Finalize pending legal documents with Muneeb
- Investor outreach
- Get started on blockstack.com and AngelList content and requirements

**Comment by jackzampolin** [comment]
_Yesterday_:
* Security meetings
* Made some help-wanted issues on `blockstack-browser`
* Forum Answers
* Various Infrastructure tasks

_Today_:
* Getting help-wanted issues on `blockstack-core`
* Mining @pstan26's video for product feedback and opening issues
* Updating the `blockstack-todo` and `blockstack-app-generator` instructions to add optional regtest setups and modernizing the `README`s
* Forum Q&A
* Continuing to setup more infrastructure alerts and adding visibility to our infra.
* Getting updated `blockstack-todo` instructions over to Mike Freedman's class

**Comment by guylepage3** [comment]
Quick Link: [Blockstack Projects](https://github.com/orgs/blockstack/projects)
- [Timeline](https://paper.dropbox.com/doc/Token-sale-timeline-October-Version-UZqEovEJ919cOQESFyMgd)
----

_**yesterday**_: 
- [x] Browser – Finalize [#465: Design active state icons for browser](https://github.com/blockstack/designs/issues/465)
- [x] Browser – [#468: New browser profile design](https://github.com/blockstack/designs/issues/468) from Frontend meeting
- [x] Blockstack.org – [#429: Update illustrations. Fonts need outlining on blockstack.org](https://github.com/blockstack/blockstack.org/issues/429)
- [x] Meeting with @shea256 on Token frontend
- [x] Blockstack.com – Worked on [#89: design the home page for token](https://github.com/blockstackinc/tokensale/issues/89)

_**today**_:
- [x] Blockstack.org – [#441: Add "sign-up" button back into hero on the home page](https://github.com/blockstack/blockstack.org/issues/441)
- [x] Token – [#470: Design token blog post image](https://github.com/blockstack/designs/issues/470)
- [x] Token – [#458: Design two PDF cover pages for token whitepapers](https://github.com/blockstack/designs/issues/458)
- [x] Token – [#111: Update blockstack.org/token to include a token whitepaper section](https://github.com/blockstackinc/tokensale/issues/111)
- [x] Token – [#459: Design new whitepaper icons](https://github.com/blockstack/designs/issues/459)
- [ ] Token – [#421: Build new privacy policy page](https://github.com/blockstack/blockstack.org/issues/421) on blockstack.org
- [ ] Token – [#109: Add disclaimer to blockstack.org](https://github.com/blockstackinc/tokensale/issues/109)
- [ ] Token – [#114: Build new privacy policy page](https://github.com/blockstackinc/tokensale/issues/114) on blockstack.com
- [ ] Token – [#108: Add disclaimer to blockstack.com](https://github.com/blockstackinc/tokensale/issues/108)

_**ahead**_:
- [ ] Browser – [#896: Add studbits app to app store](https://github.com/blockstack/blockstack-browser/issues/896)
- [ ] Blockstack.com – [#89: design the home page for token](https://github.com/blockstackinc/tokensale/issues/89)
- [ ] Blockstack.org – [#408: Build new Press Page](https://github.com/blockstack/blockstack.org/issues/408)
- [ ] Browser – [#842: Create new frame and background for browser](https://github.com/blockstack/blockstack-browser/issues/842)
- [ ] Browser – [#887: Add "DotPodcast" app to app store](https://github.com/blockstack/blockstack-browser/issues/887)
- [ ] Browser – [#847: Clean up 404 page](https://github.com/blockstack/blockstack-browser/issues/847)
- [ ] Blockstack.org – Finalize [#401: Update About page](https://github.com/blockstack/blockstack.org/issues/401)
- [ ] Blockstack.org – Finalize [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [ ] Blockstack.org – [#425: Site audit for consistency and continuity](https://github.com/blockstack/blockstack.org/issues/425)
- [ ] Blockstack.org – [#414: Add Explorer Tutorial to /tutorials page](https://github.com/blockstack/blockstack.org/issues/414)
- [ ] Browser – [#852: Add section with documentation links](https://github.com/blockstack/blockstack-browser/issues/852)
- [ ] Browser – [#815: Wallet placeholders values look like real inputs](https://github.com/blockstack/blockstack-browser/issues/815#event-1274504195)
- [ ] [#454: Resize token portfolio bounty graphic](https://github.com/blockstack/designs/issues/454)
- [ ] Token – [#452: Design CoinList UI](https://github.com/blockstack/designs/issues/452)
- [ ] Blockstack.org – [#426: Add more links and content to social share sticky footer of blockstack.org](https://github.com/blockstack/blockstack.org/issues/426)
- [ ] Onename.com – Resolve UI breakages on onename.com in Safari
- [ ] ToDo List App – Quick css live design update to to do list app

Link to today's open source design contributor standup:
- [#469: design standup – Wed, Oct 11, 2017](https://github.com/blockstack/designs/issues/469)

**Comment by jcnelson** [comment]
Yesterday:

* hardening
* security countermeasures
* fixing integration tests to be more predictable

Today: 

* hardening
* security countermeasures
* fixing integration tests to be more predictable

**Comment by muneeb-ali** [comment]
Wed:
- Working out of NJ office and got access keys etc
- Mainly focused on incorporating feedback from external reviewers for token whitepaper 
- Calls with lawyers RE token purchase agreements
