### ISSUE TITLE
Thu, Oct 12, 2017

### ISSUE THREAD

**Issue by pstan26** [blockstack/daily-standup#154]
Yesterday:
- synced with Ryan lackey about opsec
- secured more speakers for Berlin event
- Outreach to media re: token
- sourced leads w/ xan for investor meetings next week
- begun getting outside emails of investors to add to lists

Today:
- send emails out to onename users about transfer
- send token info to ICO websites
- complete sales deck and review with Ryan
- schedule more user testers
- panel at Columbia Business School in the evening on ICOs & VC

**Comment by kantai** [comment]
Yesterday:
- Work on gaia hub caching configuration
- Add copy script to the onename transfer process and update the zonefile url is publishes

Today:
- More testing of that onename transfer process
- Test Windows install from scratch

**Comment by yknl** [comment]
**Yesterday**
- Work on trust level system for profiles in browser
- Blockstack.org update

**Today**
- Finish and test trust level system
- Clean up other outstanding browser issues
- Look into adding profile search in browser

**Comment by guylepage3** [comment]
Quick Link: [Blockstack Projects](https://github.com/orgs/blockstack/projects)
- [Timeline](https://paper.dropbox.com/doc/Token-sale-timeline-October-Version-UZqEovEJ919cOQESFyMgd)
----

_**yesterday**_: 
- [x] Blockstack.org – [#441: Add "sign-up" button back into hero on the home page](https://github.com/blockstack/blockstack.org/issues/441)
- [x] Token – [#470: Design token blog post image](https://github.com/blockstack/designs/issues/470)
- [x] Token – [#458: Design two PDF cover pages for token whitepapers](https://github.com/blockstack/designs/issues/458)
- [x] Token – [#111: Update blockstack.org/token to include a token whitepaper section](https://github.com/blockstackinc/tokensale/issues/111)
- [x] Token – [#459: Design new whitepaper icons](https://github.com/blockstack/designs/issues/459)
- [x] Blockstack.com – Updates to links and buttons on the site

_**today**_:
- [x] Token – [#471: Design a token whitepaper blog post button/card](https://github.com/blockstack/designs/issues/471)
- [x] Reviewed all 200+ GitHub issue notifications on Browser, Blockstack.org, Token, etc. that have been piling up over the past few days.
- [ ] Onename.com – Resolve UI breakages on onename.com in Safari
- [ ] Blockstack.org – [#408: Build new Press Page](https://github.com/blockstack/blockstack.org/issues/408)
- [ ] Blockstack.com – [#89: design the home page for token](https://github.com/blockstackinc/tokensale/issues/89)

_**ahead**_:
- [ ] Browser – [#896: Add studbits app to app store](https://github.com/blockstack/blockstack-browser/issues/896)
- [ ] Browser – [#842: Create new frame and background for browser](https://github.com/blockstack/blockstack-browser/issues/842)
- [ ] Browser – [#887: Add "DotPodcast" app to app store](https://github.com/blockstack/blockstack-browser/issues/887)
- [ ] Browser – [#847: Clean up 404 page](https://github.com/blockstack/blockstack-browser/issues/847)
- [ ] Blockstack.org – Finalize [#401: Update About page](https://github.com/blockstack/blockstack.org/issues/401)
- [ ] Blockstack.org – Finalize [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [ ] Blockstack.org – [#425: Site audit for consistency and continuity](https://github.com/blockstack/blockstack.org/issues/425)
- [ ] Blockstack.org – [#414: Add Explorer Tutorial to /tutorials page](https://github.com/blockstack/blockstack.org/issues/414)
- [ ] Browser – [#852: Add section with documentation links](https://github.com/blockstack/blockstack-browser/issues/852)
- [ ] Browser – [#815: Wallet placeholders values look like real inputs](https://github.com/blockstack/blockstack-browser/issues/815#event-1274504195)
- [ ] Token – [#452: Design CoinList UI](https://github.com/blockstack/designs/issues/452)
- [ ] Blockstack.org – [#426: Add more links and content to social share sticky footer of blockstack.org](https://github.com/blockstack/blockstack.org/issues/426)
- [ ] ToDo List App – Quick css live design update to to do list app

Link to today's open source design contributor standup:
- [#472: design standup – Thu, Oct 12, 2017](https://github.com/blockstack/designs/issues/472)

**Comment by jackzampolin** [comment]
_Yesterday_:
- Organizing product feedback
- Updating the blockstack-todo and blockstack-app-generator instructions to add optional regtest setups and modernizing the READMEs
- Forum Q&A
- Continuing to setup more infrastructure alerts and adding visibility to our infra.
- Getting updated blockstack-todo instructions over to Mike Freedman's class

_Today_
- Edit the blockstack FAQs
- Office hours for app devs
- Discussing regtest getting started: https://forum.blockstack.org/t/setting-up-developer-environments/1782

**Comment by jcnelson** [comment]
Yesterday:

* hardening
* security countermeasures

Today: 

* hardening
* security countermeasures

**Comment by muneeb-ali** [comment]
Thur: 

- Token whitepaper [announcement](https://blockstack.org/blog/announcing-the-blockstack-token-whitepaper)
- Call with Albert 
- Call with Microsoft
- Work on finding KYC & AML providers
- Answering questions RE token paper and updating the paper with the initial community feedback
