### ISSUE TITLE
Fri, Oct 13, 2017

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/daily-standup#155]
Yesterday:

* Continued with state refactor of browser. Ran into some problems with the dropbox driver which needs to store an index URL in the user's profile. 
* Helped with token paper updates
* added cache control headers to blockstack.org api https://github.com/blockstack/blockstack.org-api/issues/1

Today:

* Will finish up browser refactoring and get it merged into develop for @shea256 's review

**Comment by pstan26** [comment]
Yesterday
Worked on presentation
coordinated with Gina about ICO site outreach
Panel at Columbia business school

Today:
User testing
presentation content review w/ Ryan

**Comment by kantai** [comment]
Yesterday
- Confirm that the profile copier is working on onename transfers
- Test registration on Windows -- found bug in the Windows deployment, plus some usability issues (launch script doesn't give an error when password fails to decrypt wallet), fixed bug.

Today
- Fix the password failure problem in the launcher script

**Comment by yknl** [comment]
**Yesterday**
- Work on trust level system in browser
- Update to blockstack.js to use name over family name and given name
- blockstack.org updates, added a loading spinner to blog posts

**Today**
- Add clearer unverified status to social proofs
- Get trust level system reviewed and merged in
- Review and work on remaining browser issues

**Comment by jackzampolin** [comment]
_Yesterday_:
- Edit the blockstack FAQs
- Office hours for app devs
- Discussing regtest getting started: https://forum.blockstack.org/t/setting-up-developer-environments/1782
- Golang implementation of the `blockstack-core` rpc interface

_Today_:
- Browser Testing
- Integration Test bugs
- `help-wanted` tasks on `blockstack-core`
- Evangelist Weekly
- Wrap up golang `blockstack-core` rpc client

**Comment by guylepage3** [comment]
Quick Link: [Blockstack Projects](https://github.com/orgs/blockstack/projects)
- [Timeline](https://paper.dropbox.com/doc/Token-sale-timeline-October-Version-UZqEovEJ919cOQESFyMgd)
----

_**yesterday**_: 
- [x] Token – [#471: Design a token whitepaper blog post button/card](https://github.com/blockstack/designs/issues/471)
- [x] Reviewed all 200+ GitHub issue notifications on Browser, Blockstack.org, Token, etc. that have been piling up over the past few days.
- [x] Onename.com – Attempted to setup python environment to resolve UI breakages on onename.com in Safari
- [x] Blockstack.com – Worked on design discovery for [#89: design the home page for token](https://github.com/blockstackinc/tokensale/issues/89)

_**today**_:
- [x] Browser – Meeting with @yknl to review [#473: Type & other important components are not highly visible](https://github.com/blockstack/designs/issues/473)
- [x] Blockstack.com/Coinlist meeting with @shea256 @muneeb-ali to review all deliverables.
- [ ] Blockstack.org – [#443: Update Patrick's bio on About page](https://github.com/blockstack/blockstack.org/issues/443)
- [ ] Onename.com – Resolve UI breakages on onename.com in Safari
- [ ] Blockstack.org – [#408: Build new Press Page](https://github.com/blockstack/blockstack.org/issues/408)
- [ ] Blockstack.com – More design discovery for [#89: design the home page for token](https://github.com/blockstackinc/tokensale/issues/89)

_**ahead**_:
- [ ] Browser – [#896: Add studbits app to app store](https://github.com/blockstack/blockstack-browser/issues/896)
- [ ] Browser – [#842: Create new frame and background for browser](https://github.com/blockstack/blockstack-browser/issues/842)
- [ ] Browser – [#887: Add "DotPodcast" app to app store](https://github.com/blockstack/blockstack-browser/issues/887)
- [ ] Browser – [#847: Clean up 404 page](https://github.com/blockstack/blockstack-browser/issues/847)
- [ ] Blockstack.org – Finalize [#401: Update About page](https://github.com/blockstack/blockstack.org/issues/401)
- [ ] Blockstack.org – Finalize [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [ ] Blockstack.org – [#425: Site audit for consistency and continuity](https://github.com/blockstack/blockstack.org/issues/425)
- [ ] Blockstack.org – [#414: Add Explorer Tutorial to /tutorials page](https://github.com/blockstack/blockstack.org/issues/414)
- [ ] Browser – [#852: Add section with documentation links](https://github.com/blockstack/blockstack-browser/issues/852)
- [ ] Browser – [#815: Wallet placeholders values look like real inputs](https://github.com/blockstack/blockstack-browser/issues/815#event-1274504195)
- [ ] Token – [#452: Design CoinList UI](https://github.com/blockstack/designs/issues/452)
- [ ] Blockstack.org – [#426: Add more links and content to social share sticky footer of blockstack.org](https://github.com/blockstack/blockstack.org/issues/426)
- [ ] ToDo List App – Quick css live design update to to do list app

Link to today's open source design contributor standup:
- [#474: design standup – Fri, Oct 13, 2017](https://github.com/blockstack/designs/issues/474)

**Comment by muneeb-ali** [comment]
Fri (and weekend): 
- Investor/community updates
- Token purchase agreements
- Work with lawyers on Operating Agreement of a LLC
- Interview with the Economist (he is not working on any story/publication in the short-term)
- SEC Ford D filing (available [here](https://www.sec.gov/Archives/edgar/data/1719379/000171937917000002/0001719379-17-000002-index.htm))
- Outreach for upcoming CA trip
