### ISSUE TITLE
Mon, Oct 23, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/daily-standup#161]
Quick Links: 
- [Blockstack Projects](https://github.com/orgs/blockstack/projects)
- [Coinlist & Blockstack.com Requirements](https://paper.dropbox.com/doc/Coinlist-Blockstack.com-FyFo57w7gYbu5DcBh5PsJ)

----

_**friday, saturday, sunday**_:
- [x] Blockstack.com – [#510: Design new countdown timer for blockstack.com](https://github.com/blockstack/designs/issues/510)
- [x] Blockstack.com – [#507: Update to blockstack.com hero section](https://github.com/blockstack/designs/issues/507)
- [x] Blockstack.com – Meeting with Barefoot and @shea256 
- [x] Blockstack.com – Coordination with Barefoot on site build
- [x] Blockstack.com – [#511: Design simple footer for blockstack.com](https://github.com/blockstack/designs/issues/511)
- [x] Blockstack.com – [#514: Add the disclaimer page back into the layout of blockstack.com](https://github.com/blockstack/designs/issues/514)
- [x] Blockstack.com – [#513: Design new privacy policy page for blockstack.com](https://github.com/blockstack/designs/issues/513)
- [x] Blockstack.org – [#447: 404 error on link from token page to token whitepaper](https://github.com/blockstack/blockstack.org/issues/447)
- [x] Blockstack.com – [#515: Update content for documents section on blockstack.com](https://github.com/blockstack/designs/issues/515)
- [x] Blockstack.com – [#512: Update to content in timeline section on blockstack.com design](https://github.com/blockstack/designs/issues/512)
- [x] Blockstack.com – Update to privacy policy content
- [x] Blocsktack.com – [#516: Move "short" disclaimer back into the footer & add page blockstack.com](https://github.com/blockstack/designs/issues/516)
- [x] Blockstack.com – [#519: Shift sections, form placement, disclaimer/privacy content for blockstack.com](https://github.com/blockstack/designs/issues/519)
- [x] Blockstack.com – Supply team with CSS for form styling
- [x] Blockstack.com – [#54: Review current state and story cards](https://github.com/blockstackinc/blockstack-dot-com/issues/54) (Sunday evening)

_**today**_:
- [x] Blockstack.com – [#520: Design confirmation upon sign up for blockstack.com](https://github.com/blockstack/designs/issues/520)
- [x] Coinlist – [#489: Design Coinlist press section](https://github.com/blockstack/designs/issues/489)
- [x] Coinlist – [#490: Design Coinlist disclaimer section](https://github.com/blockstack/designs/issues/490)
- [x] Browser – [#524: Export new svg navbar images for the browser](https://github.com/blockstack/designs/issues/524)
- [x] Coinlist – Meeting with Paul, Ryan and Muneeb
- [x] Blockstack.com – Coordination with Barefoot on site build
- [x] Computer/disk space issues.
- [ ] ›› Blockstack.com – [#517: Design image for timeline on blockstack.com](https://github.com/blockstack/designs/issues/517)
- [ ] Blockstack.com – [#518: About section content update for blockstack.com](https://github.com/blockstack/designs/issues/518) (to do after @shea256 has content)
- [ ] Coinlist – [#522: Design Coinlist footer section](https://github.com/blockstack/designs/issues/522)
- [ ] Coinlist – [#523: Design Coinlist secondary navbar](https://github.com/blockstack/designs/issues/523)
- [ ] Coinlist – [#486: Design Coinlist overview section](https://github.com/blockstack/designs/issues/486)
- [ ] Coinlist – [#487: Design Coinlist mini docs section](https://github.com/blockstack/designs/issues/487)
- [ ] Coinlist – [#488: Design Coinlist standard section](https://github.com/blockstack/designs/issues/488)

_**ahead**_:
- [ ] Blockstack.org – [#444: Add Token Whitepaper to "Papers" Section on Blockstack.org](https://github.com/blockstack/blockstack.org/issues/444)
- [ ] Blockstack.org – Add Token Banner back to website
- [ ] Blockstack.org – Move Tutorials into Main navbar between About and Docs
- [ ] Blockstack.org – Move FAQ into the Docs secondary navbar between Videos and BlockstackJS
- [ ] Blockstack.org – [#443: Update Patrick's bio on About page](https://github.com/blockstack/blockstack.org/issues/443)
- [ ] Onename.com – Resolve UI breakages on onename.com in Safari
- [ ] Blockstack.org – [#408: Build new Press Page](https://github.com/blockstack/blockstack.org/issues/408)
- [ ] Browser – [#896: Add studbits app to app store](https://github.com/blockstack/blockstack-browser/issues/896)
- [ ] Browser – [#842: Create new frame and background for browser](https://github.com/blockstack/blockstack-browser/issues/842)
- [ ] Browser – [#847: Clean up 404 page](https://github.com/blockstack/blockstack-browser/issues/847)
- [ ] Blockstack.org – Finalize [#401: Update About page](https://github.com/blockstack/blockstack.org/issues/401)
- [ ] Blockstack.org – Finalize [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [ ] Blockstack.org – [#425: Site audit for consistency and continuity](https://github.com/blockstack/blockstack.org/issues/425)
- [ ] Blockstack.org – [#414: Add Explorer Tutorial to /tutorials page](https://github.com/blockstack/blockstack.org/issues/414)
- [ ] Browser – [#852: Add section with documentation links](https://github.com/blockstack/blockstack-browser/issues/852)
- [ ] Browser – [#815: Wallet placeholders values look like real inputs](https://github.com/blockstack/blockstack-browser/issues/815#event-1274504195)
- [ ] Blockstack.org – [#426: Add more links and content to social share sticky footer of blockstack.org](https://github.com/blockstack/blockstack.org/issues/426)
- [ ] ToDo List App – Quick css live design update to to do list app

Link to today's open source design contributor standup:
- [#521: design standup – Mon, Oct 23, 2017](https://github.com/blockstack/designs/issues/521)

**Comment by kantai** [comment]
Friday - Sunday
- Add support for specifying URL in Onename exports
- Test 2-step registration process on Onename registrar (works! but not enabled yet)
- Test Windows installer in environments with Hyper-V enabled + Docker installed, the Windows installer now detects which environment it is being installed in, and uses Virtualbox + boot2docker, or just the normal Docker4Windows otherwise.

Today
- More Windows installer testing and bugfixes
- Acquiring signing certificate for Windows
- Onename backend issues

**Comment by pstan26** [comment]
Friday: 
- User testing
- PR call with coinlist folks
- brought on Sebastian for continued work
- pushed Bank accounts for LLCs forward

Today:
- Token PR outreach
- meet with exchange partners
- user testing writeup
- sign speaker contract
- onename transfer emails
- schedule designer to work on sales deck on wednesday
- Token whitepaper email

**Comment by yknl** [comment]
**Friday**
- Browser profile changes
- Analytics for blockstack.org

**Today**
- Browser profile changes
- Browser nav bar update

**Comment by muneeb-ali** [comment]
Mon: 
- Weekly meeting
- Strategy meeting with Ryan
- Token purchase agreements for existing investors (answered questions, collected signatures) 
- LLC operating agreement, reviewed allocations, updated cap table etc
- Calls RE decision on Cayman vs Delaware Fund
