### ISSUE TITLE
Tue, Oct 24, 2017

### ISSUE THREAD

**Issue by guylepage3** [blockstack/daily-standup#162]
Quick Links: 
- [Blockstack Projects](https://github.com/orgs/blockstack/projects)
- [Coinlist & Blockstack.com Requirements](https://paper.dropbox.com/doc/Coinlist-Blockstack.com-FyFo57w7gYbu5DcBh5PsJ)

----

_**yesterday**_:
- [x] Blockstack.com – [#520: Design confirmation upon sign up for blockstack.com](https://github.com/blockstack/designs/issues/520)
- [x] Coinlist – [#489: Design Coinlist press section](https://github.com/blockstack/designs/issues/489)
- [x] Coinlist – [#490: Design Coinlist disclaimer section](https://github.com/blockstack/designs/issues/490)
- [x] Browser – [#524: Export new svg navbar images for the browser](https://github.com/blockstack/designs/issues/524)
- [x] Coinlist – Meeting with Paul, Ryan and Muneeb
- [x] Blockstack.com – Coordination with Barefoot on site build
- [x] Computer/disk space issues.

_**today**_:
- [x] Computer/disk space issues.
- [x] Browser – Looked into changing the icons/navbar for the browser but decided to push this off for the next release [#526: Update navbar icons to ultramarine blue & export for browser](https://github.com/blockstack/designs/issues/526)
- [x] Blockstack.com – Reviewing site and providing feedback for Barefoot
- [x] Onename – [#368: Create HTML button for Onename email](https://github.com/blockstack/blockstack/issues/368)
- [ ] ›› Blockstack.com – [#528: Add titles to all team and advisors on blockstack.com](https://github.com/blockstack/designs/issues/528)
- [ ] Blockstack.com – [#527: Add four more investors to investor section blockstack.com](https://github.com/blockstack/designs/issues/527)
- [ ] Blockstack.com – [#517: Design image for timeline on blockstack.com](https://github.com/blockstack/designs/issues/517)
- [ ] Coinlist – [#529: Update layout of purchase to token site](https://github.com/blockstack/designs/issues/529)
- [ ] Coinlist – [#522: Design Coinlist footer section](https://github.com/blockstack/designs/issues/522)
- [ ] Coinlist – [#523: Design Coinlist secondary navbar](https://github.com/blockstack/designs/issues/523)
- [ ] Coinlist – [#486: Design Coinlist overview section](https://github.com/blockstack/designs/issues/486)
- [ ] Coinlist – [#487: Design Coinlist mini docs section](https://github.com/blockstack/designs/issues/487)
- [ ] Coinlist – [#488: Design Coinlist standard section](https://github.com/blockstack/designs/issues/488)

_**ahead**_:
- [ ] Blockstack.com – [#518: About section content update for blockstack.com](https://github.com/blockstack/designs/issues/518) (to do after @shea256 has content)
- [ ] Blockstack.org – [#444: Add Token Whitepaper to "Papers" Section on Blockstack.org](https://github.com/blockstack/blockstack.org/issues/444)
- [ ] Blockstack.org – Add Token Banner back to website
- [ ] Blockstack.org – Move Tutorials into Main navbar between About and Docs
- [ ] Blockstack.org – Move FAQ into the Docs secondary navbar between Videos and BlockstackJS
- [ ] Blockstack.org – [#443: Update Patrick's bio on About page](https://github.com/blockstack/blockstack.org/issues/443)
- [ ] Onename.com – Resolve UI breakages on onename.com in Safari
- [ ] Blockstack.org – [#408: Build new Press Page](https://github.com/blockstack/blockstack.org/issues/408)
- [ ] Browser – [#896: Add studbits app to app store](https://github.com/blockstack/blockstack-browser/issues/896)
- [ ] Browser – [#842: Create new frame and background for browser](https://github.com/blockstack/blockstack-browser/issues/842)
- [ ] Browser – [#847: Clean up 404 page](https://github.com/blockstack/blockstack-browser/issues/847)
- [ ] Blockstack.org – Finalize [#401: Update About page](https://github.com/blockstack/blockstack.org/issues/401)
- [ ] Blockstack.org – Finalize [#399: Upgrade to Bootstrap v4.0.0-beta](https://github.com/blockstack/blockstack.org/issues/399)
- [ ] Blockstack.org – [#425: Site audit for consistency and continuity](https://github.com/blockstack/blockstack.org/issues/425)
- [ ] Blockstack.org – [#414: Add Explorer Tutorial to /tutorials page](https://github.com/blockstack/blockstack.org/issues/414)
- [ ] Browser – [#852: Add section with documentation links](https://github.com/blockstack/blockstack-browser/issues/852)
- [ ] Browser – [#815: Wallet placeholders values look like real inputs](https://github.com/blockstack/blockstack-browser/issues/815#event-1274504195)
- [ ] Blockstack.org – [#426: Add more links and content to social share sticky footer of blockstack.org](https://github.com/blockstack/blockstack.org/issues/426)
- [ ] ToDo List App – Quick css live design update to to do list app

Link to today's open source design contributor standup:
- [#525: design standup – Tue, Oct 24, 2017](https://github.com/blockstack/designs/issues/525)

**Comment by yknl** [comment]
**Yesterday**
- Browser profile changes
- Browser nav bar update
- Analytics dashboard

**Today**
- Analytics dashboard
- Finish browser profile changes

**Comment by GinaAbrams** [comment]
Yesterday: 
- Got Xan onboarded 
- PM check ins 
- Resumes 
- Best Buy 

Today: 
- Returned lights 
- Safe / office upgrades 
- D&O insurance paperwork 
- Operational tasks 
- Resumes 
- Continue PM check ins

**Comment by pstan26** [comment]
Yesterday:
Sent out email about Whitepaper
Booked Jorge for wed design of deck
Onename Transfer update
Met with exchange partners
Created slack channel for princeton CS class

Today:
Thursday checklist
Join Jack & Sebastian for zendesk onboarding
Send out Onename transfer email
Big PR outreach with updated messaging
schedule more user testing
Attend DCG Summit
Blockstack Cuba

**Comment by larrysalibra** [comment]
Today:
* Working with a security review firm
* Fixed a security issue in browser where an app could request additional permissions than intended 
* Tested onename transfer feature in browser
* Update onename production with browser transfer integration
* Updated the browser-server
* Synced up with Aaron about some other security review issues
* Browser copy & did naming discussions
* Shipped v0.18.3 build

**Comment by kantai** [comment]
Today:
- Working on the native Windows system tray application and installer
- Call with prospective developers
- Sync up with Larry on security review issues
- Check on Onename registrar process
- Obtain e-mails, etc. for Onename transfer e-mail blast
- Release native installer for Windows

**Comment by muneeb-ali** [comment]
Tue: 
- Board meeting prep with Ryan
- Closed all token purchase agreements
- Worked with Ryan to log all legal doc hashes in genesis block 
- Board meeting at USV 
- Executed on all LLC agreements, sent reminders etc 
- Call RE tax withholdings issues, finalized fund location decision
