### ISSUE TITLE
Tue, Nov 21, 2017

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/daily-standup#177]
Today:
 * fixed a problem with decoding websites in our discourse forum authentication state 
 * working on re-enabling zone file & transfer pages in browser
 * weekly calls & 1 on 1 meetings

**Comment by guylepage3** [comment]
Quick Links: 
- [Blockstack Projects](https://github.com/orgs/blockstack/projects)
- [Blockstack.com Project](https://github.com/blockstackinc/blockstack-dot-com/projects/5)

----

_**yesterday**_:
- [x] Blockstack.com – Cleanup
- [x] Weekly meeting
- [x] Browser – GitHub Sprint 0.20 & 0.21 cleanup
- [x] Blockstack.com – Review team page pull request https://github.com/blockstackinc/blockstack-dot-com/pull/445
- [x] Blockstack.com – Call with @tracedwax to go over Sprint 6
- [x] Blockstack.com – Markup and copy and styling for team members, https://github.com/blockstackinc/blockstack-dot-com/issues/432
- [x] Blockstack.com – Update team page pull request https://github.com/blockstackinc/blockstack-dot-com/pull/445
- [x] Blockstack.com – Project coordination

_**today**_:
- [x] Browser – Frontend meeting w/ @larrysalibra @yknl @shea256 
- [x] Browser – Add Coinfolio to home screen https://github.com/blockstack/blockstack-browser/issues/1089
- [x] Personal meetings (x2)
- [x] Browser – Rethink Blockstack browser home screen https://github.com/blockstack/designs/issues/576
- [x] Blockstack.com – The changes you wanted to make to the legal page, https://github.com/blockstackinc/blockstack-dot-com/issues/413
- [ ] Blockstack.com – Site messaging for Dec 1 https://github.com/blockstackinc/blockstack-dot-com/issues/512

Link to today's open source design contributor standup:
- [#582: design standup – Tue, Nov 21, 2017](https://github.com/blockstack/designs/issues/582)

**Comment by muneeb-ali** [comment]
Today: 

- Working on the tail end of the token sale and helping various investors in the backlog 
- Looking into legal tasks that need attention
- Meeting with a valuation firm
- Hiring planning meeting

**Comment by yknl** [comment]
**Today**
- Added UI visual feedback to restore from keychain phrase screen
- Started work on the light weight multi-reader storage in browser
- Deploying the improved wait-list registration flow for browser web app (on hold)

**Comment by shea256** [comment]
@guylepage3 @muneeb-ali @yknl It's Tuesday today :D

**Comment by muneeb-ali** [comment]
@larrysalibra we made this the Tue scrum. Please update yours or move to Mon -- thanks!

**Comment by shea256** [comment]
Looks like we have two Tuesdays but I'll move mine here. Here's the link to Monday's scrum: https://github.com/blockstack/daily-scrum/issues/178.

**Comment by shea256** [comment]
Yesterday:

- Planning for the team meeting & the team meeting itself
- Working through the backlog of token sale investors and helping them get through the process

Today:

- Frontend planning meeting
- Working through the backlog of token sale investors and helping them get through the process
- Hiring planning meeting
- Following up on emails
