### ISSUE TITLE
Wed, Nov 22

### ISSUE THREAD

**Issue by kantai** [blockstack/daily-standup#179]
Yesterday
* Debugging `blockstack.js` encryption bug
* Start work on Onename profile fetching updates
* Explore lower confirmation preorder-registers

Today
* Onename Registrar clean-up
* More work on the Onename profile fetching updates
* Voucher registration work
* Make Windows build of Browser

**Comment by yknl** [comment]
**Yesterday**
- Frontend meeting
- Deployed improved wait-list registration to browser web app
- Fixed a few bugs on browser for the new build
- Worked on light weight multi-reader storage

**Today**
- Finish working on first part of light weight multi-reader storage

**Comment by shea256** [comment]
Yesterday:

- Frontend planning meeting
- Hiring planning meeting
- Working through the backlog of token sale investors and helping them get through the process

Today:

- Working through the backlog of token sale investors and helping them get through the process
- Meetings with reporters

**Comment by guylepage3** [comment]
Quick Links: 
- [Blockstack Projects](https://github.com/orgs/blockstack/projects)
- [Blockstack.com Project](https://github.com/blockstackinc/blockstack-dot-com/projects/5)

----

_**yesterday**_:
- [x] Browser – Frontend meeting w/ @larrysalibra @yknl @shea256 
- [x] Browser – Add Coinfolio to home screen https://github.com/blockstack/blockstack-browser/issues/1089
- [x] Personal meetings (x2)
- [x] Browser – Rethink Blockstack browser home screen https://github.com/blockstack/designs/issues/576
- [x] Blockstack.com – The changes you wanted to make to the legal page, https://github.com/blockstackinc/blockstack-dot-com/issues/413
- [x] Blockstack.com – Project coordination

_**today**_:
- [x] Personal errands
- [x] Browser – Went through all comments on issues.
- [x] Browser – Designed progress bar button for No visual indicator on restore from backup phrase https://github.com/blockstack/blockstack-browser/issues/1082
- [x] Browser – Update Arenaplay logo in next release https://github.com/blockstack/designs/issues/583
- [x] Blockstack.org – Link to mac browser on install page not current https://github.com/blockstack/blockstack.org/issues/465
- [ ] Blockstack.com – Site messaging for Dec 1 https://github.com/blockstackinc/blockstack-dot-com/issues/512
- [ ] Token – Live design token voucher email https://github.com/blockstackinc/blockstack-dot-com/issues/533
- [ ] Token – Design token voucher PDF https://github.com/blockstackinc/blockstack-dot-com/issues/534
- [ ] Browser – Wallet form text disappears on blur https://github.com/blockstack/blockstack-browser/issues/1088

Link to today's open source design contributor standup:
- [#584: design standup – Wed, Nov 22, 2017](https://github.com/blockstack/designs/issues/584)
