### ISSUE TITLE
Wed, Dec 13, 2017

### ISSUE THREAD

**Issue by xanbots** [blockstack/daily-standup#190]
_Yesterday_

- Call with MyTalengi and one other app development team
- Update call for Signature Berlin
- Worked with Patrick and Ryan on refining scope for new bounty

_Today_

- Finalize bounty and draft email and press release copy
- Call to see a demo of a chat/slack MVP created by 2 developers Satraj & Megha
- Call with an app developer looking to create digital assets in the form of clothing (t shirts) that can be bought/sold (like Cryptokitties) but are also redeemable in the real world

**Comment by GinaAbrams** [comment]
Yesterday: 
- full list of new roles from Ryan
- wrote introductory job postings for those
- wrote a first draft of internship program - looks like we may not have bandwidth for it 
- did some research into intl brand ambassadors 
- Helped move forward with payments / coinbase increase

Today: 
- Meeting with Ryan 
- Product reach out 
- D&O  E&O insurance forms 
- Quick call for R&D 
- Finalize and post all jobs 
- Quick pass over blockstack.org quick fixes (e.g update press page etc.)

**Comment by larrysalibra** [comment]
Yesterday:
* Call with a potential partner site with Patrick and Xan
* Meetings with Gina & Patrick
* Traveling

Today: 
* More traveling
* Sleep :-)

**Comment by jackzampolin** [comment]
_Yesterday_:

* Call with dotpodcast team on crawling namespaces
* Forum & Email support
* Researching Blockstack's key derivation techniques

_Today_:
* Forum & Email support
* Supporting teams building apps on blockstack
* Testing `blockstack.js` changes when they are available
* Plan work on developer default getting started experience

**Comment by yknl** [comment]
Yesterday
- Changes to browser for lightweight multi reader storage
- Updates to .org pages

Today
- `blockstack.js` changes for light-weight multi-reader storage
- Open up voucher registration on blockstack.com for early browser users

**Comment by kantai** [comment]
_Yesterday_
* blockstack.js changes in https://github.com/blockstack/blockstack.js/tree/feature/direct-gaia-hub
* Moving gaia hub signing code: https://github.com/blockstack/blockstack.js/issues/310
* Direct getFile/putFile on gaia hub: https://github.com/blockstack/blockstack.js/issues/311
* Adding hubUrl to authentication: https://github.com/blockstack/blockstack.js/issues/309
* Add 0.21.4 windows build to the browser-releases
* Fix the content-type handling of the gaia/hub
* Gave talk at Princeton Systems Seminar -- will upload slides today
* Met with Mike Freedman and got some feedback from students building on blockstack, will wrtie that up today.

_Today_
* Work on browser-side changes for the above `blockstack.js` issues (https://github.com/blockstack/blockstack-browser/issues/1119):
  1. removing core-session-token generation path when the request version is high enough
  2. update Windows/Web build path so that it allows sign-in to `storage` requesting apps (if version is high enough)

**Comment by shea256** [comment]
Yesterday:

- Prepared for my talk and spoke at The Next Web
- Made contractor payments
- Investor meeting
- Meetings with and about potential hires

**Comment by guylepage3** [comment]
Quick Links: 
- [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**monday & tuesday**_:
- [x] Monday weekly meeting
- [x] Catch up on email and Slack

_**today**_:
- [x] On vacation from Dec 11 — Dec 31
- [x] Review of all GitHub issues
- [x] Catch up on email and Slack
- [ ] Blockstack.com – Live design token mechanics page https://github.com/blockstackinc/blockstack-dot-com/issues/543
- [ ] Bounty – Design Encrypted Chat bounty eventbrite card https://github.com/blockstack/designs/issues/586
- [ ] Browser – Add Token Portfolio Apps to browser https://github.com/blockstack/blockstack-browser/issues/1108
- [ ] Blockstack.org – Docs/BlockstackJS 404 error on mobile devices https://github.com/blockstack/blockstack.org/issues/467
- [ ] Blockstack.com – Add FAQ back to site https://github.com/blockstackinc/blockstack-dot-com/issues/549

_**ahead**_:
- [ ] Auth – Update Blockstack auth button set to latest brand https://github.com/blockstack/designs/issues/596
- [ ] Auth – Design new Powered by Blockstack badge https://github.com/blockstack/designs/issues/597
- [ ] Browser – Wallet form text disappears on blur https://github.com/blockstack/blockstack-browser/issues/1088
- [ ] Start going through issues that are back-logged as discussed w/ @shea256 

Link to today's open source design contributor standup:
- [#600: design standup – Wed, Dec 13, 2017](https://github.com/blockstack/designs/issues/600)
