### ISSUE TITLE
Fri, Dec 15, 2017

### ISSUE THREAD

**Issue by xanbots** [blockstack/daily-standup#192]
_Yesterday_

- Finalized bounty, began working on collateral
- Coordinated bounty graphic w/ Guy
- Coordinated edits to /funding page with Eric Stermer

_Today_

- Finish drafting collateral for bounty - copy for blog post, email copy, Press release, Eventbrite page
- Coordinate promotion of token bounty apps for next Wednesday
- Send Eric Stermer all collateral for changes to /funding page
- Intro Call w/ Jet

**Comment by GinaAbrams** [comment]
Yesterday: 
- Lowered inbox of resumes / careers@ / angellist
- 2 candidate calls
- Copy writer candidate sourcing 
- Synced with Ryan re: product managers 

Today: 
- Make sure form D filing happens 
- Sync with Ryan on last items to submit D&O E&O insurance 
- Candidate reach out - product, copywriter, designer 
- Sync with Pat / Jim about building recruiting pipeline  
- AngelList resumes 
- post jobs 
- pay BTC

**Comment by guylepage3** [comment]
Quick Links: 
- [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**wednesday, thursday**_:
- [x] Review of all GitHub issues
- [x] Catch up on email and Slack

_**today**_:
- [x] On vacation from Dec 11 — Dec 31
- [x] Review of all GitHub issues
- [x] Catch up on email and Slack
- [ ] Blockstack.com – Live design token mechanics page https://github.com/blockstackinc/blockstack-dot-com/issues/543
- [ ] Bounty – Design Encrypted Chat bounty eventbrite card https://github.com/blockstack/designs/issues/586
- [ ] Browser – Add Token Portfolio Apps to browser https://github.com/blockstack/blockstack-browser/issues/1108
- [ ] Blockstack.org – Docs/BlockstackJS 404 error on mobile devices https://github.com/blockstack/blockstack.org/issues/467
- [ ] Blockstack.com – Add FAQ back to site https://github.com/blockstackinc/blockstack-dot-com/issues/549

_**ahead**_:
- [ ] Auth – Update Blockstack auth button set to latest brand https://github.com/blockstack/designs/issues/596
- [ ] Auth – Design new Powered by Blockstack badge https://github.com/blockstack/designs/issues/597
- [ ] Browser – Wallet form text disappears on blur https://github.com/blockstack/blockstack-browser/issues/1088
- [ ] Start going through issues that are back-logged as discussed w/ @shea256 

Link to today's open source design contributor standup:
- [#601: design standup – Fri, Dec 15, 2017](https://github.com/blockstack/designs/issues/601)
