### ISSUE TITLE
Tue, Dec 19, 2017

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/daily-standup#194]
Yesterday:
* started warning for name registration
* engineering meeting
* weekly meetings
* met up with community member in hong kong interested in the economics of blockstack token system

Today: 
* Wrote draft of a engineering process/checklist for calling & holding meetings, pull requests and weekly planning
* Started testing light-weight multi-reader storage

**Comment by kantai** [comment]
Yesterday
* Engineering meeting / Weekly meeting
* Fix up changes to blockstack-browser for the new `blockstack.js` features

Today
* Thawing the transaction generation in JS user story (won't complete this sprint, but I'll work on it until something else comes up)

**Comment by GinaAbrams** [comment]
Yesterday: 
- Weekly meeting 
- Scheduling / catching up with candidates 
- Put together list of roles we're hiring for and some context for team 
- Going through the candidate source list Jim gave us 

Today: 
- Call with another HR manager for more info on benefits etc. 
- Call w potential copywriter 
- Product Manager sourcing 
- Designer sourcing 
- Find additional FAQ from forum posts and slack 
- Finalize and send out the jobs list

**Comment by yknl** [comment]
Yesterday
- Team meeting
- Engineering meeting
- Test and debug light multi-reader storage changes

Today
- Make new browser build
- More testing and documentation for light-weight multi-reader storage

**Comment by jackzampolin** [comment]
Yesterday
* Weekly Meeting
* Eng Meeting
* Spoke with developers building apps on Blockstack

Today
* Calls with developers building apps on Blockstack
* Support (Forum & Tickets)
* Adding alerting

**Comment by xanbots** [comment]
_Yesterday_

Worked on new bounty
Team meetings, going to have a growth meeting (growth, BD, marketing, signature fund) every Tuesday starting in January
Worked on promotion for portfolio apps when they go live

_Today_

Finalize new bounty for tomorrow
Finalize everything for token portfolio apps to be launched tomorrow
Signature Berlin meeting

**Comment by pstan26** [comment]
Yesterday:
- Post production call with Zach on Ryan's TNW talk
- Worked on Bounty announcement for Wed (will continue today)
- Call with Community Developer candidate (w/ Ryan)

Today:
- Wrapping up last edits with DevLink before sending folks there tomorrow
- Call with new Health records co intro’d by VC
- Berlin Status call
- 2018 Growth Planning & Budgeting

**Comment by shea256** [comment]
Today:

- [x] Meetings with potential partners
- [x] Meeting with Aaron to brainstorm in-browser transactions
- [x] Get an important document notarized and mailed
- [x] Create some visuals around the Blockstack platform
- [x] Mark up the bounty requirements doc
- [x] Mark up the token portfolio announcement doc
- [x] Mark up the decentralize communication post
- [x] Provide edits and updates to the hiring plan document

**Comment by guylepage3** [comment]
Quick Links: 
- [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**monday**_:
- [x] Browser – Add Token Portfolio Apps to browser https://github.com/blockstack/blockstack-browser/issues/1108

_**today**_:
- [x] On vacation from Dec 11 — Dec 31
- [x] Browser – Add new Coinstack app icon to browser https://github.com/blockstack/blockstack-browser/issues/1108
- [x] Signature Fund – Design Eventbrite image for Encrypted & Decentralized P2P Messaging Bounty https://github.com/blockstackinc/design/issues/11
- [x] Signature Fund – Design Eventbrite image for Group Messaging Bounty https://github.com/blockstackinc/design/issues/12
- [x] Signature Fund – Design blog post image for Decentralize Communication Bounty https://github.com/blockstackinc/design/issues/13

_**ahead**_:
- [ ] Blockstack.com – Live design token mechanics page https://github.com/blockstackinc/blockstack-dot-com/issues/543
- [ ] Bounty – Design Encrypted Chat bounty eventbrite card https://github.com/blockstack/designs/issues/586
- [ ] Blockstack.org – Docs/BlockstackJS 404 error on mobile devices https://github.com/blockstack/blockstack.org/issues/467
- [ ] Blockstack.com – Add FAQ back to site https://github.com/blockstackinc/blockstack-dot-com/issues/549
- [ ] Auth – Update Blockstack auth button set to latest brand https://github.com/blockstack/designs/issues/596
- [ ] Auth – Design new Powered by Blockstack badge https://github.com/blockstack/designs/issues/597
- [ ] Browser – Wallet form text disappears on blur https://github.com/blockstack/blockstack-browser/issues/1088
- [ ] Start going through issues that are back-logged as discussed w/ @shea256 

Link to today's open source design contributor standup:
- [#603: design standup – Tue, Dec 19, 2017](https://github.com/blockstack/designs/issues/603)
