### ISSUE TITLE
Fri, Dec 22, 2017

### ISSUE THREAD

**Issue by xanbots** [blockstack/daily-standup#198]
_Yesterday_

- New bounty sign ups
- Calls with Morgan Stanley and Jet
- Cleared out inbox

_Today_

- Promote new bounty on social platforms
- 3 calls with developers
- Clear out inbox again

**Comment by GinaAbrams** [comment]
Yesterday:
- 4 interviews
- Copy reach out 
- Product Sourcing 

Today: 

- [ ] travel arrangements for cand 

- [ ] sync with Ryan

- [ ] Send out a couple swag items 

- [ ] Candidate reach out

**Comment by kantai** [comment]
Yesterday
* Work on automated Windows builds -- only remaining item here is that the new MSI doesn't detect installs from the previous installers
* Work on setting up integration test suite for transaction generation in `blockstack.js` -- made pretty good progress here, took me a little while to get docker to set up the bitcoind and blockstack integration suite so that I could communicate with both from node, but should have some passing tests today

Today
* Continue work on the above two items
* Engineering meeting
* Process name registrations for a couple of onename users whose names expired

**Comment by guylepage3** [comment]
Quick Links: 
- [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**tuesday, wednesday, thursday**_:
- [x] Signature Fund – Make changes to blog post image for Bounty to Decentralize Communication https://github.com/blockstackinc/design/issues/13
- [x] Signature Fund – Make requested change to Eventbrite image for Group Messaging Bounty https://github.com/blockstackinc/design/issues/12
- [x] Browser – Discussion around Isotach Replace `Ongaku Ryoho` with its newer version `Isotach` https://github.com/blockstack/blockstack-browser/issues/1137

_**today**_:
- [x] On vacation from Dec 11 — Dec 31
- [ ] Browser – Replace `Ongaku Ryoho` with its newer version `Isotach` https://github.com/blockstack/blockstack-browser/issues/1137
- [ ] Browser – Add DevLink to browser https://github.com/blockstack/blockstack-browser/issues/1139

_**ahead**_:
- [ ] Blockstack.com – Live design token mechanics page https://github.com/blockstackinc/blockstack-dot-com/issues/543
- [ ] Bounty – Design Encrypted Chat bounty eventbrite card https://github.com/blockstack/designs/issues/586
- [ ] Blockstack.org – Docs/BlockstackJS 404 error on mobile devices https://github.com/blockstack/blockstack.org/issues/467
- [ ] Blockstack.com – Add FAQ back to site https://github.com/blockstackinc/blockstack-dot-com/issues/549
- [ ] Auth – Update Blockstack auth button set to latest brand https://github.com/blockstack/designs/issues/596
- [ ] Auth – Design new Powered by Blockstack badge https://github.com/blockstack/designs/issues/597
- [ ] Browser – Wallet form text disappears on blur https://github.com/blockstack/blockstack-browser/issues/1088
- [ ] Start going through issues that are back-logged as discussed w/ @shea256 

Link to today's open source design contributor standup:
- [#605: design standup – Fri, Dec 22, 2017](https://github.com/blockstack/designs/issues/605)

**Comment by yknl** [comment]
Yesterday
- Review + make PR changes for multi reader storage

Today
- Engineering meeting
- Finalize multi reader storage API

**Comment by shea256** [comment]
Today:

- [x] Engineering meeting
- [x] Larry 1-on-1
- [x] Patrick 1-on-1
- [x] Gina 1-on-1
- [x] Xan 1-on-1
- [x] Lawyer call
- [x] Provide ownership details to Gina so she can submit insurance forms
- [x] Get documents notarized for lawyers

This weekend:

- [ ] 1 hour of product manager outreach
- [ ] Provide feedback on hiring doc
- [ ] Deposit checks
- [ ] Look up Libratax info from Nomad email
- [ ] Search inbox for General Liability Insurance
