### ISSUE TITLE
Mon, Jan 8, 2018

### ISSUE THREAD

**Issue by guylepage3** [blockstack/daily-standup#203]
Quick Links: 
- [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**thursday, friday**_:
- [x] Marketing meeting
- [x] Managing developer requests for asssets
- [x] Worked on review Brand
- [x] Worked on review Browser
- [x] Worked on review Brand Guide
- [x] Worked on review Design System

_**this week**_:
- [x] Weekly team meeting
- [ ] Review Brand
- [ ] Review Browser
- [ ] Review Brand Guide
- [ ] Review Design System
- [ ] Meet with Ken to discuss design goals
- [ ] Create a Design Roadmap including quarterly, bi-annual & annual goals separated by product
- [ ] Meet with Ryan and Ken about final design goals
- [ ] Write list of what a design team can do and the roles that they would play

_**ahead**_:
- [ ] Browser – Replace `Ongaku Ryoho` with its newer version `Isotach` https://github.com/blockstack/blockstack-browser/issues/1137
- [ ] Browser – Add DevLink to browser https://github.com/blockstack/blockstack-browser/issues/1139
- [ ] Blockstack.com – Live design token mechanics page https://github.com/blockstackinc/blockstack-dot-com/issues/543
- [ ] Bounty – Design Encrypted Chat bounty eventbrite card https://github.com/blockstack/designs/issues/586
- [ ] Blockstack.org – Docs/BlockstackJS 404 error on mobile devices https://github.com/blockstack/blockstack.org/issues/467
- [ ] Blockstack.com – Add FAQ back to site https://github.com/blockstackinc/blockstack-dot-com/issues/549
- [ ] Auth – Update Blockstack auth button set to latest brand https://github.com/blockstack/designs/issues/596
- [ ] Auth – Design new Powered by Blockstack badge https://github.com/blockstack/designs/issues/597
- [ ] Browser – Wallet form text disappears on blur https://github.com/blockstack/blockstack-browser/issues/1088
- [ ] Start going through issues that are back-logged as discussed w/ @shea256 

Link to today's open source design contributor standup:
- [#608: design standup – Mon, Jan 8, 2018](https://github.com/blockstack/designs/issues/608)

**Comment by xanbots** [comment]
**Today**

- Weekly meeting
- New bounty promotion
- Signature Berlin presentation
- 2 calls with developer teams

**Comment by jcnelson** [comment]
Friday:
* work on refactoring blockstackd chain state db

Today:
* weekly meeting
* work on refactoring blockstackd chain state
* prepare for engineering meeting

**Comment by larrysalibra** [comment]
Today: 
* wrote up interview notes for Gina
* added checks for app origin in the authentication request verification process to blockstack.js
* updated browser to use it
* added some test coverage to a portion of our auth process
* 1-on-1s with ryan & muneeb
* weekly meeting

Tomorrow's plan:
* review weekly meeting doc and create sprint items
* merge app origin check stuff
* review & test multi-reader storage PRs and help as necessary with test coverage
* triage issues/planning

**Comment by jackzampolin** [comment]
_Friday_:
* Worked on finding a replacement for `utxo.blockstack.org`
* Monitoring and alerting
* Infrastructure tasks

_Today_:
* Team Weekly
* UTXO replacement work
* Working on cataloguing the infrastructure and listing tech debt

**Comment by shea256** [comment]
Today:

- [x] 1-on-1 w/ Larry
- [x] Founder preparation meeting
- [x] Weekly meeting
- [x] Financial planning meeting
- [x] Work on product plan
- [x] M. meeting
- [x] V. meeting
- [x] Lawyer meeting
- [x] 1-on-1 w/ Guy

**Comment by GinaAbrams** [comment]
Today:
- Call with Withum re: R&D Tax credit
- Collected and submitted 409A info
- Upcoming interviews planning / check in / next steps 
- Financial materials for E 
- Bill.com / Nomad sync 
- Went through some submitted resumes 
- Candidate call 
- Mkting x crypto list sourcing

**Comment by yknl** [comment]
Today
- Weekly meeting
- Multi-storage tutorial draft + video
- Get demo app up and running

**Comment by muneeb-ali** [comment]
Mon:

- Weekly meeting
- 1-on-1 meetings with Larry, Jack, Jude, and Aaron 
- Meeting for organizing financial data and modeling it
- Finalized 409a firm and had introductory call 
- Call with lawyers and CoinList RE pending legal tasks 
- Decentralized Identity Foundation working group meeting
- Email catch up
