### ISSUE TITLE
Thu, Jan 11, 2017

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/daily-standup#207]
Yesterday:
* Post mortem meeting
* Call with jack
* Created remaining sprint user story items
* Merged pull request on blockstack repo
* Triaged blockstack.js issues
* Tested and deployed security fix to browser.blockstack.org
* Helped to test multi-reader storage demo app
* Shipped blockstack.js v0.15.0

Today:
* Review name registration warning copy
* Continue triaging issues

**Comment by kantai** [comment]
Yesterday:
* Transaction generation written and tested for transfers
* Transaction generation written for renewals
* Hire meetings
* Netlify headers for browser.blockstack.org
* Fix an issue with integration testing on blockstack-core in docker

Today:
* Wrap up transaction testing
* Test multi-player storage
* Open a PR for blockstack-core for announcing zonefiles

**Comment by jackzampolin** [comment]
_Yesterday_:

* Issue triage and cleanup and repo cleanup.

_Tomorrow_: 

* Issue triage and repo cleanup 
* Engineering meeting 🤞 
* Hiring and Growth meeting
* Systemd unit files for our services

**Comment by jcnelson** [comment]
Today:
* deprecate storage RPC calls in blockstackd (now handled by Gaia hubs)
* clean up and deprecate unused BlockstackDB code
* disentangle consensus code from chainstate code (which now lives wholly in virtualchain)
* patch test framework to accommodate changes to the chainstate databases
* extend virtualchain abstract chain interface to handle querying the chain length, to fetch transactions by block range, and to parse transactions into a canonical data structure
* bizdev phone calls

**Comment by xanbots** [comment]
_Yesterday_
- Promoted new bounties on Product Hunt
- Call with DOE
- Call with Nucleos
- Gov. use case meeting
- Worked with Shannon on Signature Berlin

_Today_
- Growth meeting
- Promote new bounties on github
- 4 calls with teams developing apps
- Help Shannon with any Signature Berlin work

**Comment by guylepage3** [comment]
Quick Links: 
- [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**monday**_:
- [x] Weekly team meeting
- [x] Worked on review Brand
- [x] Worked on review Browser
- [x] Worked on review Brand Guide
- [x] Worked on review Design System
- [x] Performance review with Ryan S

_**tuesday, wednesday**_:
- [x] Sick both days

_**today**_:
- [x] Sat in on engineering meeting
- [x] Growth meeting
- [x] Hiring meeting
- [ ] Finalize browser review 
- [ ] Finalize brand review

_**this week**_:
- [ ] Finalize brand guide review
- [ ] Finalize design system review
- [ ] Meet with Ken to discuss design goals
- [ ] Create a Design Roadmap including quarterly, bi-annual & annual goals separated by product
- [ ] Meet with Ryan and Ken about final design goals
- [ ] Write list of what a design team can do and the roles that they would play
- [ ] Finalize new design process in order set and measure design/brand/front-end goals

_**ahead**_:
- [ ] Browser – Replace `Ongaku Ryoho` with its newer version `Isotach` https://github.com/blockstack/blockstack-browser/issues/1137
- [ ] Browser – Add DevLink to browser https://github.com/blockstack/blockstack-browser/issues/1139
- [ ] Blockstack.com – Live design token mechanics page https://github.com/blockstackinc/blockstack-dot-com/issues/543
- [ ] Bounty – Design Encrypted Chat bounty eventbrite card https://github.com/blockstack/designs/issues/586
- [ ] Blockstack.org – Docs/BlockstackJS 404 error on mobile devices https://github.com/blockstack/blockstack.org/issues/467
- [ ] Blockstack.com – Add FAQ back to site https://github.com/blockstackinc/blockstack-dot-com/issues/549
- [ ] Auth – Update Blockstack auth button set to latest brand https://github.com/blockstack/designs/issues/596
- [ ] Auth – Design new Powered by Blockstack badge https://github.com/blockstack/designs/issues/597
- [ ] Browser – Wallet form text disappears on blur https://github.com/blockstack/blockstack-browser/issues/1088
- [ ] Start going through issues that are back-logged as discussed w/ @shea256 

Link to today's open source design contributor standup:
- [#609: design standup – Thu, Jan 11, 2018](https://github.com/blockstack/designs/issues/609)

**Comment by GinaAbrams** [comment]
Yesterday:

- Circle with E regarding 409a materials
- sourcing for marketing / growth / designers
- call with F regarding salary bands, skills interview templates
- call with N
- nomad stuff 

Today: 
- growth meeting 
- hiring meeting 
- organize financial/legal files 
- candidate sourcing

**Comment by shea256** [comment]
Today's Meetings:

- [x] Marketing meeting
- [x] Hiring meeting
- [x] Goals and roadmap meeting w/ Muneeb - Part 1

Today's Tasks:

- [x] Write up a list of additional hires to consider
- [x] Writeup list of key hires and metrics for marketing meeting
- [x] Provide feedback on token incentives proposal
- [x] Respond to MC email
- [x] Circle back on two investor requests

**Comment by jcnelson** [comment]
Today:
* meetings, meetings, meetings
* remove legacy virtualchain logic for setting a global working directory and a global implementation (this made sense when virtualchain used a multiprocess blockchain crawler, but it hasn't done this for some time).
* disentangle virtualchain global variable dependencies from the atlas subsystem
* disentangle virtualchain global variable dependencies from the integration test framework
* debug chainstate replay logic in virtualchain
* deprecate the use of `blockstack_client` to back up zone files in the atlas crawler
* begin disentangling blockstack-core from `blockstack_client`

**Comment by yknl** [comment]
Yesterday
- Debug multi-reader demo app + help devs with testing
- Multi-reader storage release
- 1 on 1 with ryan
- Tutorial video

Today
- Multiple meetings
- Make browser build v0.22.0 with multi-player storage
- Tutorial video

**Comment by muneeb-ali** [comment]
Thur:

- Meeting RE 2018 roadmap (main focus) 
- Growth meeting
- Hiring meeting
- Work on finishing out legal work on some investments
