### ISSUE TITLE
Tue, Jan 16, 2017

### ISSUE THREAD

**Issue by kantai** [blockstack/daily-standup#210]
_Yesterday_
* Weekly meeting
* Helped out transaction generation for a couple users in support queue
* Opened discussion thread for transaction generation in `blockstack.js` integration
* Work on smarter profile writes in browser

_Today_
* Continue work on browser profile writes
* Investigate safety checks for blockstack.js blockstack transactions

**Comment by xanbots** [comment]
_Yesterday_
- Weekly meeting
- Signature Berlin status call
- Call with developer of CoinKitty
- Bounty promotion

_Today_
- Call with Rocket.Chat/Aragon teams
- Bounty Call
- Growth Meeting
- App intros to VCs
- Bounty promotion

**Comment by muneeb-ali** [comment]
Mon:

- Weekly Meeting
- 1-on-1s with Larry, Jack, and Ken
- Calls with Cooley RE some upcoming corporate tasks
- Feedback on Signature Berlin
- Support for Blockstack token (inbound email) 
- Sort out travel (Volkswagen talk)
- Email catch up (this will likely be a recurring task this week given my backlog)

**Comment by GinaAbrams** [comment]
Mon: 
- Weekly meeting 
- Jack Insurance 
- Preliminary hiring priority list 
- COO Sourcing 
- Job recs 
- Market price research

Tuesday: 
- Hiring sync 
- Realtor 
- Candidate sourcing 
- Growth meeting 
- Continue writing job recs 
- Operational catch up

**Comment by jackzampolin** [comment]
_Yesterday_:
- Weekly meeting
- Finished Issue Triage
- Finally wrapping up long standing support issue ([`psommariva.id`](https://explorer.blockstack.org/name/psommariva.id))
- 1-1 With Muneeb
- Answered outstanding issues on the forum
- Health Insurance with @GinaAbrams (Thank you! 🙌 )


_Tomorrow_:
- [Harden `node.blockstack.org`](https://github.com/blockstack/blockstack/issues/400)
- [DevOps Plan 2018](https://github.com/blockstack/blockstack/issues/401)
- Growth Meeting
- Discuss Issue Tagging with [team](https://forum.blockstack.org/t/issue-tagging-for-blockstack/3974)

**Comment by guylepage3** [comment]
Quick Links: 
- [Blockstack Projects](https://github.com/orgs/blockstack/projects)

----

_**tuesday, wednesday, thursday, friday, monday**_:
- [x] Sick days

_**today**_:
- [ ] Finalize browser review 
- [ ] Finalize brand review
- [ ] Add banner that links to Berlin event https://github.com/blockstack/blockstack.org/issues/483
- [ ] Quick meeting @muneeb-ali on blockstack.org requirements/tasks

_**this week**_:
- [ ] Finalize brand guide review
- [ ] Finalize design system review
- [ ] Meet with Ken to discuss design goals
- [ ] Create a Design Roadmap including quarterly, bi-annual & annual goals separated by product
- [ ] Meet with Ryan and Ken about final design goals
- [ ] Write list of what a design team can do and the roles that they would play
- [ ] Finalize new design process in order set and measure design/brand/front-end goals

_**ahead**_:
- [ ] Browser – Replace `Ongaku Ryoho` with its newer version `Isotach` https://github.com/blockstack/blockstack-browser/issues/1137
- [ ] Browser – Add DevLink to browser https://github.com/blockstack/blockstack-browser/issues/1139
- [ ] Blockstack.com – Live design token mechanics page https://github.com/blockstackinc/blockstack-dot-com/issues/543
- [ ] Bounty – Design Encrypted Chat bounty eventbrite card https://github.com/blockstack/designs/issues/586
- [ ] Blockstack.org – Docs/BlockstackJS 404 error on mobile devices https://github.com/blockstack/blockstack.org/issues/467
- [ ] Blockstack.com – Add FAQ back to site https://github.com/blockstackinc/blockstack-dot-com/issues/549
- [ ] Auth – Update Blockstack auth button set to latest brand https://github.com/blockstack/designs/issues/596
- [ ] Auth – Design new Powered by Blockstack badge https://github.com/blockstack/designs/issues/597
- [ ] Browser – Wallet form text disappears on blur https://github.com/blockstack/blockstack-browser/issues/1088
- [ ] Start going through issues that are back-logged as discussed w/ @shea256 

Link to today's open source design contributor standup:
- [#610: design standup – Tue, Jan 16, 2018](https://github.com/blockstack/designs/issues/610)

**Comment by yknl** [comment]
Yesterday
- Weekly Meeting
- Enhancements to MR demo app
- Tutorial video editing
- 1 on 1 with muneeb
- Help devs with issues

Today
- Draft for blog entry
- Video editing

**Comment by muneeb-ali** [comment]
Tue:

- Call with a team of engineers who're working on chat bounty
- Video recording for the Upfront summit
- Sync up on hiring (and offers)
- Meeting with tax accountant 
- Meeting with 409a firm
- Interview with potential hire 
- A draft (initial thoughts) of 2018 roadmap

**Comment by shea256** [comment]
Tuesday tasks:

- [x] Update product roadmap and share with the team
- [x] Create a spreadsheet modeling out hires
- [x] Send out offer details to candidate

Tuesday meetings:

- [x] Hiring sync-up meeting
- [x] Compensation meeting w/ Muneeb
- [x] S. hiring interview
