### ISSUE TITLE
Wed, Jul 19, 2017

### ISSUE THREAD

**Issue by vsund** [blockstack/daily-standup#94]
Yesterday: Had to rethink the generic attributes, re-implemented them, should be good know, implemented validation of votes, updated tests

Today: Finish layout/design, fix errors with non-working imports, begin implementing TXT records

**Comment by jay-ithiel** [comment]
Yesterday: Met with Jude & Patrick about multi-user storage and adding comments on blogs.
Guild - Added ability to edit blogs and styled the userblogs page. Made user profile component skeleton
Casa - Changed input types and style for HomeForm to make it more like the Bedkin app

Today: Meet with Scott about Bedkin Casa app. 
Casa - Continue styling HomeForm for responsive design
Guild - Add content to user profile component and style

**Comment by muneeb-ali** [comment]
Today: Closing deals for hosting our infrastructure, getting reviews on our tax strategy and finalizing it, legal housekeeping, and meetings with law firms and a potential hire. Also, did some general planning for token tasks.

**Comment by guylepage3** [comment]
_**yesterday**_: 
- Continued working on reviewing pull request for @estermer
- Finalized researching `git flow`
- [x] Finalized designs for on-boarding screens
- [x] Redesigned status bar to look more like a browser
- [x] Built new status bar file for sharing with design team
- [x] Reviewed 

_**today**_:
- [ ] Merge @yknl's PR https://github.com/blockstack/blockstack-browser/pull/630: Design update to profile view into browser
- [ ] Merge @estermer's PR https://github.com/blockstack/blockstack-browser/pull/626: Fixed Flexbox for Safari into browser
- [ ] Finalize review pull request process for @estermer
- [ ] https://github.com/blockstack/blockstack-browser/issues/634: Update the Status Bar items and design to new design
- [x] https://github.com/blockstack/blockstack-browser/issues/637: build ui of on-boarding screens
- [ ] https://github.com/blockstack/blockstack-browser/issues/632: Auto-generate large profile
- [ ] https://github.com/blockstack/blockstack-browser/issues/625: design photo upload page in profile editing section
- [ ] https://github.com/blockstack/blockstack-browser/issues/570: build new "create profile" button in profiles app
- [ ] https://github.com/blockstack/blockstack-browser/issues/635: Move profile list view below auto-generated profile
- [ ] https://github.com/blockstack/blockstack-browser/issues/370: create design requirements for the registration process
- [ ] https://github.com/blockstack/blockstack-browser/issues/220: update ui of profile card in profile app
- [ ] https://github.com/blockstack/blockstack-browser/issues/260: ui build of live search query view inside profiles app
- [ ] https://github.com/blockstack/blockstack-browser/issues/636: move the storage providers should be at the top within the settings choices
- [ ] https://github.com/blockstack/blockstack-browser/issues/262: ui build of edit profile pages inside the profiles app
- [ ] https://github.com/blockstack/blockstack-browser/issues/261: design of edit profile pages inside the profiles app
- [ ] https://github.com/blockstack/blockstack-browser/issues/259: design live search query view inside profiles app
- [ ] https://github.com/blockstack/blockstack-browser/issues/258: live design new profiles app register pages

_**ahead**_:
- [ ] Pull in UI from `Profiles` utility into `Wallet` utility for consistency amongst browser utilities.
- [ ] Pull in UI from `Profiles` utility into `Settings` utility for consistency amongst browser utilities.
- [ ] https://github.com/blockstack/blockstack.org/issues/323: update hero design
- [ ] UI build of project Apollo website design
- [ ] Create prototype links and sync on-boarding screen layouts to invision browser prototype [Browser v0.11 (Desktop)](https://invis.io/W7CDXKIFA)
- [ ] Review @arisgk pull request on blockstack.org
- [ ] Resolve symbols in sketch `browser-v0.11.sketch` file
- [ ] Fix SASS grid in `blockstack-bootstrap`
- [ ] Ensure we're using `20px` gutters in the `blockstack-boostrap` grid system
- [ ] Add grid to `browser-v0.11.sketch` file
- [ ] Add "edit profile" designs to `browser-v0.11.sketch`
- [ ] Create prototype links and sync edit profile layouts to invision browser prototype [Browser v0.11 (Desktop)](https://invis.io/W7CDXKIFA)

Link to today's open source design contributor standup:
- https://github.com/blockstack/designs/issues/347
